### ISSUE TITLE
New feature: Radio-button-list

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-cards/button-card#102]
What I am missing is to tag buttons, so they behave like a group of buttons, like in a radio-button list.
If I press  button no. 1, in the group, the otter buttons in the group goes off. If I press button no. 2 in the group,  button no. 2 goes on, the otter buttons in the group goes off etc.
A new option like, rb_group: “myRbg1”, to each button in a group.
This can be done now, with an automation and switches, in backend. But why not in the GUI?

**Comment by iantrich** [comment]
Sounds like a different card type

**Comment by RomRider** [comment]
@Tom-ahawk, this should be handled by scripts and/or automation. The frontend is not there to manage logic, it's there to display things.

**Comment by a005** [comment]
@RomRider, I'd like to see possibility to  to represent an input_select like a set of radio-button corresponding to input_select options. I can't find custom card for it. Making script/automation/(helpers entity for each option of input_select) it is wrong way (this is not a bussiness logic this is UI logic). Button card is a good alternative to keep it on UI level.
