### ISSUE TITLE
Help adding a space between name and state!

### ISSUE THREAD

**Issue by Norien** [custom-cards/button-card#103]
I just updated to `0.1.1` and noticed that the name and state now stack vertically vs horizontal on `0.0.8`

I was able to play around and get the alignment back to horizontal with a style tag
```
style:
  - display: flex
  - justify-content: center
```
but I cannot seem to get a space between the name and state no matter what I try.
here is a screenshot of my old frontend on `0.0.8`
![frontend_old](https://user-images.githubusercontent.com/8930713/56432562-d8e74980-629b-11e9-9dbc-ba627ffa95bd.png)

and now the new on `0.1.1`
![frontend](https://user-images.githubusercontent.com/8930713/56432607-f87e7200-629b-11e9-83b5-5a82f3199c57.png)

I'm getting closer to what I want but defiantly need some help getting the space back! 
Edit** - My lovelace is over here - https://github.com/Norien/Home-Assistant-Config/blob/master/ui-lovelace.yaml

**Comment by B3voholic** [comment]
I'm missing this as well!  Would love to see it return.

**Comment by RomRider** [comment]
@Norien @B3voholic it happens because we changed the `span` to a `div`. Waiting for a bunch or PR to be merged in and I will start working on this just after.
Lots of good stuff incoming! 🙂

**Comment by RomRider** [comment]
@Norien @B3voholic, see PR #108 and please give me feedback on the different layouts.

**Comment by Norien** [comment]
This is amazing! I can already think of a few cases where I'd like to have a tiny `icon - state` as well as my usual `name: state` 

I can't wait for this!
