### ISSUE TITLE
Toggle doesn't work for locks

### ISSUE THREAD

**Issue by jamesdawson3** [custom-cards/button-card#110]
I believe this is a HA limitation, but toggle action doesn't toggle lock domain entities.  My simple workaround is as follows:

Change lines 542-547:
```
          case 'toggle':
          default:
            this.hass.callService('homeassistant', 'toggle', {
              entity_id: state.entity_id,
            });
            break;
```
to
```
          case 'toggle':
          default:
            if( state.entity_id.split('.', 2)[0] == 'lock'){
              if( state.state == 'locked' ){
                this.hass.callService('lock', 'unlock', {
                  entity_id: state.entity_id,
                });
              } else if( state.state == 'unlocked' ){
                this.hass.callService('lock', 'lock', {
                  entity_id: state.entity_id,
                });
              }
            } else if( state.entity_id.split('.', 2)[0] == 'cover'){
              if( state.state == 'open' ){
                this.hass.callService('cover', 'close_cover', {
                  entity_id: state.entity_id,
                });
              } else if( state.state == 'closed' ){
                this.hass.callService('cover', 'open_cover', {
                  entity_id: state.entity_id,
                });
              }
            } else {
              this.hass.callService('homeassistant', 'toggle', {
                entity_id: state.entity_id,
              });
            }
            break;
```

Hopefully this helps others. 

EDIT: Apparently this is also true for covers - added cover functionality too.

**Comment by jer78** [comment]
The alternative is to make a template switch and use that instead.

**Comment by RomRider** [comment]
If we start with locks, we'll have to cover the default for each entity type and each state of each entity type.
As there are workarounds for now (templates), we'll set it to low priority.

**Comment by jamesdawson3** [comment]
Thanks for the comments guys.  The more I think about this, the more I agree - the workaround shouldn't live in a Lovelace card.  Really the change should be made to the HA core to include toggle for the lock, cover, etc domains.  I think I'll change to template switches for now.

**Comment by RomRider** [comment]
This will be fixed once we move everything to typescript @jamesdawson3 ! :)
See #122

**Comment by jamesdawson3** [comment]
Works exactly as expected!  Well done, thank you!
