### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by kmlucy** [custom-cards/button-card#113]
I just upgraded to 0.3.0, and am now getting this error: ``https://FQDN/customcards/button-card.js:6:1 Uncaught SyntaxError: Unexpected token export``

**Comment by RomRider** [comment]
Can you show me your lovelace resource config please?

**Comment by kmlucy** [comment]
I got it working. I had it as ``type: js`` rather than ``type: module``. Did that change recently? Or was it just luck that it was working before?

**Comment by RomRider** [comment]
It might just be luck that it worked before 😊

**Comment by kmlucy** [comment]
Interesting, thanks. Also, are you able to delete this issue? Or is there someone else who can? It's not the biggest deal, but I'd prefer my Home Assistant URL not be public, and while I changed the title, there isn't a way to remove the old title from the issue history.

**Comment by RomRider** [comment]
@iantrich, can you delete this issue please? I don't have the proper access right to do it.

**Comment by iantrich** [comment]
N9. But I updated the text

**Comment by kmlucy** [comment]
@iantrich It's actually the original title that I need removed, not the text of the issue:

![image](https://user-images.githubusercontent.com/13952475/56499505-b12ef600-64d4-11e9-8cae-d49232031345.png)

**Comment by iantrich** [comment]
Ah. No I can't delete it.
