### ISSUE TITLE
Feature Request: Show Attribute Instead of State

### ISSUE THREAD

**Issue by apop880** [custom-cards/button-card#120]
I'd like an option to display an entity's attribute on a button instead of the state. My use case would be for a light, if it's off I'd like to show the state of Off, but if it's on, I'd like to see the current brightness.

**Comment by RomRider** [comment]
There's something quite similar in #112, but your use case is a bit different as you'd like to show the state or something else based on the state. The current plan is to always show the state and/or some other attribute independently of the state.
Going to think about this.
We might introduce templates support in the future...

For now maybe you can try with the [config-template-card](https://github.com/custom-cards/config-template-card) ?

**Comment by apop880** [comment]
I think config-template-card may work for me, I'll give it a shot.

**Comment by jarrah31** [comment]
+1 for templates support!
