### ISSUE TITLE
Tooltip on button

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-cards/button-card#127]
Is it possible to set a &quot;help-text&quot; or see the button name, when hovering over the button?

![image](https://user-images.githubusercontent.com/35527507/56821626-268d2480-684f-11e9-8ba5-911f0d9aefc0.png)

Making a panel of buttons with icons, be able to see the name or a help-text when hovering the button would be a welcomed feature.

**Comment by RomRider** [comment]
That is now implemented in `3.4.0-1`.
