### ISSUE TITLE
Repeat option for hold_action

### ISSUE THREAD

**Issue by apop880** [custom-cards/button-card#147]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice to be able to repeatedly take an action if a button is pressed and continues to be held. For example, this would be useful for volume increase/decrease commands to repeat on a remote control setup.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by iantrich** [comment]
You need to release to trigger actions. Additionally on browsers, if you hold for too long you'll bring a context menu

**Comment by RomRider** [comment]
@iantrich, done in #148 :) If you want to have a look at the PR, might be good to integrate this into your helper.

**Comment by RomRider** [comment]
@apop880, would you mind trying this [this file](https://raw.githubusercontent.com/custom-cards/button-card/repeat/dist/button-card.js) with the new code that supports `repeat` in your setup and use it a bit to give me feedback please? See the PR #148 for how to configure it.

**Comment by apop880** [comment]
@RomRider you are awesome! I'll do some testing later today!

**Comment by iantrich** [comment]
🎉 nicely done!

**Comment by iantrich** [comment]
@RomRider I'd gladly accept a PR for it ;)

**Comment by RomRider** [comment]
Will do :)

**Comment by apop880** [comment]
Tested successfully!

**Comment by RomRider** [comment]
While we're at it, I've also added a new double tap action 😋

**Comment by iantrich** [comment]
Dude is in 🔥!!

**Comment by iantrich** [comment]
Well now you need to add double tap to the helpers as well ;)

**Comment by RomRider** [comment]
I plan to migrate all the things to the npm module helpers, I will do all this in one shot! ;)
