### ISSUE TITLE
Tried to serve up '/config/www/github/custom-cards/button-card.js.map' but it does not exist

### ISSUE THREAD

**Issue by johntdyer** [custom-cards/button-card#157]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I have tried this in Safari and Firefox and I get this error in the logs

```
2019-05-13 08:38:41 ERROR (MainThread) [custom_components.custom_updater] Tried to serve up '/config/www/github/custom-cards/button-card.js.map' but it does not exist
```

In Firefox console logs I get the following;
```
Source map error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
Resource URL: https://automation.xxxx/customcards/github/custom-cards/button-card.js?track=true
Source Map URL: button-card.js.map[Learn More]
```

**Version of the card**
Version:  1.8.0 
Home Assistant: 0.92.2

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**
<img width="801" alt="image" src="https://user-images.githubusercontent.com/58234/57622588-eec6f200-755b-11e9-90d5-467fb9ffe2b1.png">

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser Firefox 66.0.5 (64-bit) and Safari Version 12.1 (14607.1.40.1.4)

**Additional context**

**Comment by RomRider** [comment]
You can safely ignore this error. This map file is a file that gets automatically generated for debugging purpose, I'm going to see if I can release the file without it.

**Comment by johntdyer** [comment]
> `And by the way, the type is module not js in the resources.``

@RomRider  - Where did I say it was js vs module ?

**Comment by RomRider** [comment]
I was wondering about the strange issue in FF, that's why ;)
