### ISSUE TITLE
allow more-info to point to other entities

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#163]
**Additional context**

following our discussion in https://community.home-assistant.io/t/lovelace-button-card/65981/1141?u=mariusthvdb

please add the option for a more-info action to point to other entities than the entity holds.

previously on Tiles:

```
entities:
  - entity: device_tracker.life360_name
    templates:
      background: >
        if (state === 'home' || state === 'not_home') return 'url(\"/local/tiles/family/name_' + state + '.png\")';
        return 'url(\"/local/tiles/family/name_' + entities['sensor.name_location_picture'].state + '.png\")';
      style: >
        if (state === 'home') return 'background-color: #008000';
        if (state === 'not_home') return 'background-color: #808080';
        return 'background-color: #643aac';
    more_info: group.name
```

**Comment by iantrich** [comment]
I was planning on adding this to the common custom-card-helpers in the near future; so lets table this until we convert to those helper functions
