### ISSUE TITLE
Configuration template not working with icon overwrite

### ISSUE THREAD

**Issue by StijnVdd** [custom-cards/button-card#165]
**Is your feature request related to a problem? Please describe.**
I defined some button templates and reuse them trough my configuration. On of the things I do is configuring:
`state:
      - value: "on"
        styles:
          state:
            - color: '#DD5555'`

In the button where I used this template I specify the 'icon' for the "on" state. (Different per button)

**Describe the solution you'd like**
The result should show the icon specified on the button itself and together with the styles specified in the template. In general it would be a good idea to prioritize the config specified on the button itself. eq. when an icon is specified in the template AND on the button itself, the value on the button should be used.

**Describe alternatives you've considered**

**Additional context**

**Comment by RomRider** [comment]
It's expected and written in the documentation that states are not merged but appended (second bullet point here):
https://github.com/custom-cards/button-card/blob/master/README.md#configuration-templates

**Comment by StijnVdd** [comment]
That is why I opened a FR...

**Comment by RomRider** [comment]
It's valid but I don't think I'm going to put that in place. It will require that states are defined in the same order in both the template and the config. It will lead to a lot of confusion for everyone.

**Comment by StijnVdd** [comment]
maybe add a tag 'id' to make it easy to correlate them in the backend. I agree it would lead to a lot of confusion, but I think that the fact you can overload everything except the state creates the same level of confusion. Please consider this FR maybe for a future release.

Thanks a lof for the fast and clear responses!

**Comment by RomRider** [comment]
`id` is a good idea to merge the states, I'll add that.

**Comment by StijnVdd** [comment]
Super! Looking good!

Thanks for the fast implementation!
