### ISSUE TITLE
background-image in style

### ISSUE THREAD

**Issue by robertw** [custom-cards/button-card#180]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
background image shows fine in chrome on pc but on phone chrome browser background image does not show....

**Version of the card**
Version: 1.10.2

**To Reproduce**
This is the configuration I used:
``` - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: "custom:button-card"
            entity: switch.theater_on
            color: auto
            icon: mdi:movie
            action: toggle
            name: Ceiling
            style:
              - font-size: 12px
              - font-weight: bold
              - background-image: url("/local/background/al1.jpg")
              - background-size: 100% 100%
              - border-radius: 20px
              - border: solid 1px rgba(100,100,100,0.3)
#          color: rgb(51, 51, 255)
              - box-shadow: 3px 3px rgba(0,0,0,0.6)

```

**Screenshots**

**Expected behavior**
background image to show

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 74.0.3729.169 

**Smartphone (please complete the following information):**
 - Device: Samsung s9+
 - OS: [e.g. iOS8.1]android 9
 - Browser stock chrome
 - Version 74.0.3729.157

**Additional context**
Add any other context about the problem here. background image shows fine i chrome on pc but on phone chrome browser background image does not show....

**Comment by RomRider** [comment]
`style` is deprecated since 1.10.0 so if you see something on your desktop browser it means that your browser is still using its cached version and your mobile phone not.

Replace style with styles:
```yaml
styles:
  card:
    - stuff here
```
Clear the cache everywhere and retry.
Thanks
