### ISSUE TITLE
Potentially a feature request - use buttons as keypad

### ISSUE THREAD

**Issue by christmasjumper** [custom-cards/button-card#191]
Hi,

I have a lovelace view I am building. I want to be able to type a number using individual number buttons I have on the page (I so far have a button each for 0 through 9), and then for this number to be sent to a particular service when I press another button. The tricky bit is the number could be up to 6 digits long.

My current plan is to some how work out how to get each of the buttons to concatonate the button number that is pressed to a system wide variable. The “go” button will then iniaite a script and pass the current value of the variable to the script and in turn to the service (whilst also clearing the variable shortly after so it’s ready for next use)

Is there an easier way of doing this? Perhaps something using templates? I am not sure if variables are accesible directly from the templates?

**Comment by RomRider** [comment]
That's not possible using only button-card unfortunately. Each button is independent from each other.
However maybe calling a script from each button that would append a value to an existing number in a input_number entity type would probably cover your use case ;)
