### ISSUE TITLE
Add an option to configure the Lock time

### ISSUE THREAD

**Issue by DavidFW1960** [custom-cards/button-card#192]
**Is your feature request related to a problem? Please describe.**

The default hard coded 5 seconds for the lock is too long.

**Describe the solution you'd like**

**Describe alternatives you've considered**
I’d like to be able to set the lock ‘open’ time in the configuration instead of it being hard wired as it is now.

**Additional context**

**Comment by iantrich** [comment]
@RomRider added this to the restriction-card the other day FWIW https://github.com/custom-cards/restriction-card/commit/f8b5e4c096933ec8e681a3f8a38db8234ee5bcdb

**Comment by RomRider** [comment]
Thanks @iantrich, done. :)

**Comment by DavidFW1960** [comment]
Thanks Jerome. Fix works great.
