### ISSUE TITLE
Expose "label" in "label_template"

### ISSUE THREAD

**Issue by JesseWebDotCom** [custom-cards/button-card#194]
When using "label_template", I'd like to be able to access the provided "label" value in the javascript code.  Here's a super simple example:

```
label: 40.5
label_template: >
  return Math.round(label);
```

**Comment by RomRider** [comment]
I'm not sure I see the use case for that.

Is your label value provided as a variable from elsewhere/another card?
And if so, why not round that value elsewhere then?

**Comment by JesseWebDotCom** [comment]
Imagine I'm using a common button card template because I want all my main buttons looking the same.  For each entity type (ex. light, fan, etc), I want the label formatted differently:
- light = entity.attributes.brightness
- fan = entity.attributes.speed
- climate = Math.round(entity.attributes.temperature)
- other = just use the label provided

Makes sense.  Ideas to do it another way simply?

**Comment by RomRider** [comment]
I don't see how accessing the `label` in a template would help you to achieve that as label is static text.
You can use 4 templates which reference each the common template.
You can chain templates together i.e. reference another template from within a template. That would do exactly what you want.

**Comment by RomRider** [comment]
You can do it like this if you want only 1 template:
```yaml
label: >
  switch (entity.entity_id.split('.')[0]) {
    case 'light':
      return entity.attributes.brightness;
      break;
    case 'fan':
      return entity.attributes.speed;
      break;
    ...
  }
```
