### ISSUE TITLE
Install with hass.io add-on store

### ISSUE THREAD

**Issue by MickL** [custom-cards/button-card#196]
Is there a way to install it by use of the Hass.io add-on store? I put in the repository URL but it does not find the module. If it is not possible please consider this as a feature request :)

**Comment by RomRider** [comment]
That's not possible, an add-on is a docker image this is just a custom card for lovelace, however you can use : https://github.com/custom-components/hacs which is the same thing but for custom cards :)

**Comment by MickL** [comment]
Thanks :)
