### ISSUE TITLE
Add option to make dropdown-list

### ISSUE THREAD

**Issue by mredone** [custom-cards/button-card#20]
Is there a chance to add options, where after clicking on the button, next button are shown underneath
example, after clicking "living room" button, underneath i have buttons from light switches, info from all sensors?

**Comment by RomRider** [comment]
I think you should try with the [pop-up card](https://github.com/thomasloven/lovelace-popup-card)

**Comment by Norien** [comment]
I've done this a couple times by having an input boolean switch on/off and a conditional card to show and hide!
