### ISSUE TITLE
cannot change entity_picture

### ISSUE THREAD

**Issue by prankousky** [custom-cards/button-card#211]
Hi everbody,

I just installed `button-card` attempting to display different user photos depending on their state. While my code works for `name`, it will **not** work for `entity_picture`. First example code works fine, second will not display anything.

```
type: 'custom:button-card'
entity: device_tracker.me
name: |
  [[[ if (entity.state == 'home')
    return "i am home";
  else
    return "i am not home";
  ]]]

```

This will change the name below the icon (currently just a person's silhouette) to *i am home* / *i am not home* depending in the actual state. I then tried this

```
type: 'custom:button-card'
entity: device_tracker.ben_s9plus_van
entity_picture: |
  [[[ if (entity.state == 'home')
    return "/local/iamhome.jpg";
  else
    return "/local/iamaway.jpg";
  ]]]
```

I tried similar code for `icon`, which would also work just fine. Only `entity_picture` leaves me hanging.

I also tried removing the path, but `return "iamaway.jpg"` (assuming that it will look in that directory by default) does not work, either. What am I doing wrong? Btw. my goal is to have a "regular" (color) picture per person that is home and the same picture in b/w when they are away that I want to display depending on the status.

EDIT: Oh and I also tried using a URL instead of using a local file; that would also not work.

Would somebody please help me fix this? Thank you in advance for your support :)

**Comment by RomRider** [comment]
Did you add `show_entity_picture: true` ?

**Comment by prankousky** [comment]
> Did you add show_entity_picture: true ?

I added it just now after reading your comment and it works!! Thank you so much.
