### ISSUE TITLE
Settting tap & hold action to 'none' results in calling the turn_on service

### ISSUE THREAD

**Issue by MarsWarrior** [custom-cards/button-card#213]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
If I set the tap & hold action to 'none', the button still want's to call the turn_on service.
However, I don't want the button to do anything on user tap/hold/whatever.

Error in browser:
`Cannot call service binary_sensor/turn_on Service not found.
`

![image](https://user-images.githubusercontent.com/1220775/62824396-4a297000-bb9d-11e9-9747-0296d4557fc9.png)

**Version of the card**
Version: 2.05

**To Reproduce**
This is the configuration I used:
```yaml
  tap_action:
    action: none
    haptic: light
  hold_action:
    action: none
    haptic: heavy
```

**Screenshots**
See above

**Expected behavior**
If both tap and hold are set to none, I would expect the button to be read-only, but the cursos changes to a hand if hovering above the button, and pressing the mouse button results in the given error.

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version [66]

**Additional context**

**Comment by RomRider** [comment]
I can't reproduce, could you please show me your whole button config and the templates if there is any?

**Comment by AmoebeLabs** [comment]
I will try a few things. I see now that these buttons are part of a decluttering template. 

Will try a 'naked' button-card to see if the problem is in the button-card or in the decluttering template or a strange combination.

**Comment by MarsWarrior** [comment]
Oops, forgot to change accounts 😄
