### ISSUE TITLE
Can you add homekit jelly special effects?

### ISSUE THREAD

**Issue by morestart** [custom-cards/button-card#218]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by morestart** [comment]
you can see it in homekit app, if you click the button, the button gets bigger and then becomes normal size immediately.

**Comment by RomRider** [comment]
I don't have homekit, so I don't know what you're talking about. Maybe with gif would help?

**Comment by morestart** [comment]
you can see it
[](https://s2.ax1x.com/2019/09/11/ndr5TJ.th.gif)

**Comment by RomRider** [comment]
I don't think I'll implement that, it's not consistent with home-assistant overall.

**Comment by morestart** [comment]
well, thanks for your reply

Jérôme W. <notifications@github.com> 于2019年9月25日周三 下午1:50写道：
