### ISSUE TITLE
specify number of buttons

### ISSUE THREAD

**Issue by snizzleorg** [custom-cards/button-card#22]
Would be great if the number of buttons that fit into one horizontal line could be specified or if that is not possible the minimum width. I try to fit 5 buttons into one line and depending on the width of the column the 5th does not show up.

**Comment by kuuji** [comment]
@snizzleorg I believe this is an issue with the horizontal stack card. Right now it always tries to put them horizontally, even if there's not enough space.

There's not much I can do unfortunately, it would require a change to horizontal stack itself.

**Comment by snizzleorg** [comment]
@kuuji thanks.

**Comment by galoz11** [comment]
same problem here,
hope for a fix
thank you

**Comment by kuuji** [comment]
@galoz11 again, not much I can do. Are you using an horizontal stack?

**Comment by RomRider** [comment]
Wait for PR #97 for the icons to be aligned in the center but even without it, I manage to have 10 buttons on the same line, please reopen this issue if it's still a problem. Thanks

![Home_Assistant](https://user-images.githubusercontent.com/21064206/56422323-16050900-62a7-11e9-88e7-9942aaa99adb.jpg)
