### ISSUE TITLE
"Custom element doesn't exist" errors in older iOS devices

### ISSUE THREAD

**Issue by trimethia** [custom-cards/button-card#221]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
A red message with the text `Custom element doesn't exist: button-card` is displayed in older iOS devices (tested with iPhone 6s on Safari running iOS 10.3.3) in Home Assistant. The card displays fine with an up-to-date, desktop version of Safari on a mac. 

When the above error happens in my iOS device, Home Assistant outputs the following log:
`button-card.js:69.0 SyntaxError: Cannot declare a const variable twice: 't'`

After a quick search I believe this is due to a Safari ES6 bug. There seems to be a work-around using mangle options and uglify:
https://bugs.webkit.org/show_bug.cgi?id=171041
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/92#issuecomment-324818437

Is there any way to build the card with any workaround so that it works in older iOS devices? 
I'd rather prefer not to update my iOS device at this time. Thanks in advance. 

**Version of the card**
Version: 2.0.5

**Version of Home Assistant**
Version: 0.99.3

**Expected behavior**
Card is displayed.

**Comment by trimethia** [comment]
Here are the errors thrown by web inspector for my iOS device:

<img width="1025" alt="Screen Shot 2019-10-04 at 9 46 06" src="https://user-images.githubusercontent.com/16490054/66173623-04b08d00-e68c-11e9-91be-ad0585859994.png">

**Comment by iantrich** [comment]
Would require compiling with Babel. Kind of a pain for a dev to have to configure. PRs welcome

**Comment by trimethia** [comment]
Thanks, I am not really familiar with Babel but will give it a try.

**Comment by trimethia** [comment]
@iantrich Just verified that just adding a terser option solves the issue in my case: https://github.com/custom-cards/button-card/pull/222
