### ISSUE TITLE
Can the entire locking functionality be pulled out into it's own card?

### ISSUE THREAD

**Issue by Fredderic** [custom-cards/button-card#225]
There's a couple cards that have locking features, and an entity row card with locking, but many many more cards that SHOULD have locking.

Further, this cards locking feature is generic enough it sould do well as it's own thing, essentially wrapping other cards, including this one.  This cards built-in locking could then be depreciated, and any further development towards it go there instead.

---

Was thinking about trying to tackle this myself, but I'm still fairly new to custom cards, and with the comments about the complexities of adding the card-in-button support with regards to click handling…  I think I'll just make this an FR for the experts to handle, instead.

My plan was essentially:

```yaml
lock-card
    confirmation: string
    unlock_users: [...]
    card:
      type: "custom:button-card"
      entity: switch.test
```
- locks the contained card from accidental manipulation (not a secure feature)
- if unlock_users is specified, only those users can unlock the card (default: anyone)
- if confirmation message is specified, prompt user before unlocking the contained card
- further styling and so forth would follow…  (dimming locked card, moving the lock icon, etc.)
- some way for a contained button-card to style differently when locked?

**Comment by RomRider** [comment]
@iantrich worked on creating that card, it's there: [restriction-card](https://github.com/custom-cards/restriction-card)
