### ISSUE TITLE
Create an icon_name_state3rd with everything aligned horizontally and icon, name and state are concatenated and centered

### ISSUE THREAD

**Issue by lsilva171** [custom-cards/button-card#226]
**Is your feature request related to a problem? Please describe.**
I want to have a custom button with icon, name and state aligned horizontally and centered
**Describe the solution you'd like**
Create an icon_name_state3rd with everything aligned horizontally and icon, name and state are concatenated and centered
**Describe alternatives you've considered**
Currently using two custom button cards to almost achieve the same layout. It's a waste of resources and layout still off
**Additional context**

**Comment by RomRider** [comment]
You can do that using custom styles and custom fields if required.
