### ISSUE TITLE
Template support for embedded cards config

### ISSUE THREAD

**Issue by CMaxim77** [custom-cards/button-card#239]
First, Thank You for everything you do for our community and the future of this passion of ours!

I just wanted to know if it would be possible to template embedded cards?

ie:

            custom_fields:
                slider:
                  card:
                    type: custom:slider-entity-row
                    full_row: true
                    hide_state: true
                    hide_when_off: true
                    entity: light.chandelier #### Templated to use the same entity as the original one specified in the button card

![button card](https://user-images.githubusercontent.com/34638986/67919274-23644f80-fb76-11e9-944a-aaf9ffe455ba.png)

**Comment by RomRider** [comment]
I'll add this to the next release 👍

**Comment by RomRider** [comment]
This will be the solution once the next version is released: `entity: '[[[ return entity.entity_id ]]]'`
