### ISSUE TITLE
Installation link returns 404

### ISSUE THREAD

**Issue by jayheavner** [custom-cards/button-card#243]
Just FYI. The download link is referencing /dist which isn't in the repo. Simple enough to clone, install, and build but it might trip some folks up.

**Comment by RomRider** [comment]
Thanks, I'll fix that. The file is in the release section of the repository no need to build it yourself.

**Comment by m90att** [comment]
Tripped me up.  where can i get the .js file to install please?  I can't see a release section

**Comment by RomRider** [comment]
Here: https://github.com/custom-cards/button-card/releases

**Comment by RomRider** [comment]
Duplicate of #251

**Comment by RomRider** [comment]
Fixed in 6dc0573cf7a5802da96c2c1b20009fd5f5e120e1
