### ISSUE TITLE
Dynamically return color

### ISSUE THREAD

**Issue by jayheavner** [custom-cards/button-card#244]
I'm trying to set a color based on light brightness but it's not working. It's always black.

Here's an example:
```
      color: >
        [[[
            var bri = states['light.bedroom'].attributes.brightness;
            return 'rgb(248, 222, ' + (bri ? bri : 0) + ')';
          ]]]      

```

However, this does work.
`      color: "${states['light.living_room'].attributes.brightness < 50 ? 'rgb(255, 255, 0)' : 'rgb(255, 255, 125)'}"
`

If I move it to the name attribute just to check it returns as expected:
```
      name: |
        [[[
          var bri = states['light.bedroom'].attributes.brightness;
          return 'rgb(248, 222, ' + (bri ? bri : 0) + ')';
        ]]] 
```

Actually, this also works
```
      color: >-
        ${'rgb(255, 255, ' + states['light.living_room'].attributes.brightness + ')'}

```

**Comment by RomRider** [comment]
You can just use `color: auto` it will result in what you want to do.

**Comment by jayheavner** [comment]
Oh, that's super easy. Can I change the base color?

**Comment by RomRider** [comment]
What do you mean by base color?
