### ISSUE TITLE
Reopen issue #195

### ISSUE THREAD

**Issue by fmonday** [custom-cards/button-card#247]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
Toggle action on iOS platforms causes the entity to turn on and then immediately off unless a ~1-second hold is perfectly executed. 

**Version of the card**
3.0.0

**To Reproduce**
see my addendum to issue #195

**Comment by iantrich** [comment]
Can confirm. Seeing the same issue in my custom cards and is also present in core.

**Comment by fmonday** [comment]
I've been experimenting with this, and for some reason the issue is far more pronounced using the HA iOS app on an iPad pro than it is on an iPhone. Maybe that's helpful somehow.

**Comment by wixoff** [comment]
Confirmed here too, on my iPad 2018 but seemingly not on my iPhone 7 plus.  Both using iOS Companion 2.0 from the app store.

**Comment by RomRider** [comment]
Will be fixed in the next release.

**Comment by fmonday** [comment]
This is fixed on iPhone, but weirdly not on my 2018 iPad Pro. Still exactly the same
HA 0.105.1
iOS 13.3
