### ISSUE TITLE
manual installation file from readme  throws 404. 

### ISSUE THREAD

**Issue by xerxes87** [custom-cards/button-card#251]
Opening manual installation file from readme  throws 404.

**Comment by GitHubLuigi** [comment]
Hi,

You can download the file here: 
https://github.com/custom-cards/button-card/releases/download/3.0.0/button-card.js

And after that you should add the version number (3.0) to the url in the raw editor:  
 - type: module
    url: /local/button-card.js?v=3.0

Then it works great!

**Comment by RomRider** [comment]
Close in 6dc0573cf7a5802da96c2c1b20009fd5f5e120e1
