### ISSUE TITLE
[FR] Support for multiple entities

### ISSUE THREAD

**Issue by daphatty** [custom-cards/button-card#256]
I'd like to request the addition of support for multiple entities, similar to the way auto-entities can inject and create multiple unique entries within the same card based on filtered criteria (i.e. all entities within a light and switch domain). The ultimate goal would be to enable auto-button-card creation for any entity that meets the filtered criteria, which would be especially useful when adding new devices into Home Assistant.

**Comment by RomRider** [comment]
That would be another card actually. We already had some discussion about it on the forum. I'll see if I can come up with something that is not too hacky.

**Comment by iantrich** [comment]
This can already be done with layout-card: https://github.com/thomasloven/lovelace-layout-card#a-few-tips
