### ISSUE TITLE
Button card causes error in cast.home-assistant.io

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#262]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**

When casting from Chrome to my Google Hub (https://cast.home-assistant.io/), I see the instance, but all button cards are red, with error 'cannot read property 'config' of null'

**Version of the card**
Version: 
3.0.0
**To Reproduce**
This is the configuration I used:
```yaml

```
any card based in custom:button-card

**Screenshots**
![4d9cce4eac52edc5bd264bda14e2c40e2ace5255](https://user-images.githubusercontent.com/33354141/71764967-f07c6600-2eee-11ea-8a8c-45de5df265d1.jpeg)

**Expected behavior**

**Desktop (please complete the following information):**

Chrome 79.0.3945.88 (Officiële build) (64-bits)

**Smartphone (please complete the following information):**

**Additional context**
please see community discussion [from here](https://community.home-assistant.io/t/lovelace-button-card/65981/2811?u=mariusthvdb)

**Comment by RomRider** [comment]
@Mariusthvdb fixed in the next release :)
