### ISSUE TITLE
Slider-entity-row + CSS styling with card-mod problem when embedded into button-card

### ISSUE THREAD

**Issue by septeven** [custom-cards/button-card#268]
Hello there,

I'm using button-card along with Thomas Loven's card mod and slider-entity-row.
The slider is embedded into a button-card as a custom-field that controls a light entity. That part works perfectly.

I'm also applying some CSS rules to this slider (using card-mod), and I've correctly figured out how to to proceed. That part works too, BUT the slider won’t keep the CSS styling - after a few seconds or as soon as I’m shifting the slider, the custom CSS style disappears.

Note that this problem is not showing up when the slider is not embedded into your button-card.

I have looked into it through Chrome (and Safari) dev tools inspector and noticed that the button-card seems to refresh its CSS style (--button-card-light-color, --button-card-light-color-no-temperature ...) pretty frequently - in order to update the light entity hue/brightness/.... I guess.

Is there any chance that might be related to what I'm encountering ? 
Is button-card refresh its CSS style frequently when using a light entity ? If so, would it be possible to have an option to deactivate the update/refresh feature so it might help me to get rid of that glitch... ?

Thanks ;)

**Comment by RomRider** [comment]
can you use `mod-card` instead of just the `style` entry on the slider and report back?
See: https://github.com/thomasloven/lovelace-card-mod#mod-card

**Comment by RomRider** [comment]
Closing, solution is here: https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/293
