### ISSUE TITLE
More-info anomaly on rightside iPhone screen

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#272]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**

been seeing this for a while, but because of some dark background on my buttons, didn’t really see the issue.
disabled the color, and then see it more clearly: on my iPhone, doing a more-info on hold action on buttons near the righthand side (where the scroll bar resides) of the screen results in odd behavior, described best as the full screen pulling back (a bit like a tsunami) and quickly restoring to the front again.

This seems to have to do with the grey circle (which appears when holding) touching the right side (scrollbar)

I must touch the buttons most left side, so this circle doesn’t touch the scrollbar and then things are alright.
otoh, the closer one gets to the scrollbar, the more vehement the effect becomes
Doesn't happen in a desktop browser as far as I can see

**Version of the card**
Version: 
3.1.1
**To Reproduce**
This is the configuration I used:
```yaml
  hold_action:
    action: more-info
    haptic: success
```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

iPhone 13 pro, iOS 13.3
**Additional context**

**Comment by RomRider** [comment]
A recording of the screen when this happens would be nice. I don't own an iPhone to test unfortunately.

Thanks

**Comment by Mariusthvdb** [comment]
![20200120_071943000_iOS](https://user-images.githubusercontent.com/33354141/72707200-30368500-3b60-11ea-886b-6e4780309b85.gif)

please let me know this is clear enough

**Comment by RomRider** [comment]
I don't think this is something I can fix. It seems related to how hass displays the whole screen :/

**Comment by Mariusthvdb** [comment]
too bad, thanks for having a look though.
Would this be something for the frontend team then? Since it only happens on the buttons I fear they wont accept an issue, Button card being a custom card...

**Comment by RomRider** [comment]
It should happen with the default button also, would you mind trying please?

**Comment by Mariusthvdb** [comment]
yes it does! Ive never even used the core button card ;-)

on mobile it is even more difficult to see, because I dont get the grey circle when holding the button. I can see the effect happen though when holding the button near the right hand side

**Comment by RomRider** [comment]
It's because the circle overflows the screen size so it's expanded. I'm not sure how to fix that unfortunately... This is probably again some random CSS craziness 😅

**Comment by RomRider** [comment]
Does this still happen with the 0.110 *and* 3.3.5?

**Comment by matt8707** [comment]
https://github.com/home-assistant/frontend/issues/11320

**Comment by Mariusthvdb** [comment]
can be closed (not custom:button-card, and fixed in core HA)
