### ISSUE TITLE
Change icon and colour based on a sensor state instead of based on the button state

### ISSUE THREAD

**Issue by Korte68** [custom-cards/button-card#274]
**Is your feature request related to a problem? Please describe.**

Change icon and colour based on a sensor state instead of based on the button state 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RomRider** [comment]
You can do that already, please read the documentation here on github.

**Comment by Korte68** [comment]
Thank you,

I tried, but I'm not an expert...

Can you help me with some hint?

Thank you

Jérôme W. <notifications@github.com> ezt írta (időpont: 2020. jan. 22.,
Sze, 19:11):

**Comment by iantrich** [comment]
@Korte68 use the forums for support. Github is for bugs/feature requests
https://community.home-assistant.io/t/lovelace-button-card/65981
