### ISSUE TITLE
Use light.all as entity to switch

### ISSUE THREAD

**Issue by stefanroelofs** [custom-cards/button-card#275]
Button has no effect when I use "light.all" as entity. Nothing happens when I press this button:
```
  - type       : custom:button-card
    entity     : light.all
    name       : Switch all lights
```

My end goal is to turn off all lights in the house, like this:
```
  - type       : custom:button-card
    entity     : light.all
    name       : Switch off all lights
    icon       : mdi:lightbulb-multiple
    show_icon  : true
    color_type : icon
    color      : "#5ade02"
    tap_action:
      action   : call-service
      service  : "light.turn_off"
      service_data:
        entity_id: light.all
    lock:
      enabled  : true
      duration : 30
      unlock   : tap

```

**Comment by iantrich** [comment]
It should be `entity_id: all` in the service data

**Comment by stefanroelofs** [comment]
Thanks for your response. That fixed the Turn_off service call!
There is 1 more thing I'm seeing:

Take this example:
```
- type         : custom:button-card
    entity     : light.all
    name       : Switch all lights
```
The button will be On constantly. (So it lights up). No matter if any of my lights are on or off.

No big issue for me, so no action required.
Thanks!

**Comment by iantrich** [comment]
That's not a real entity
