### ISSUE TITLE
Feature request: Directly show a live stream without pressing the button 

### ISSUE THREAD

**Issue by friendodevil** [custom-cards/button-card#277]
**Is your feature request related to a problem? Please describe.**
Button card to directly show (without pressing the button) a live stream off an ONVIF camera

**Describe the solution you'd like**
Display live stream on button without pressing the button

**Describe alternatives you've considered**
N/A

**Additional context**
screen shot, camera setup at [this link](https://community.home-assistant.io/t/lovelace-button-card/65981/2955)

**Comment by RomRider** [comment]
Will be available in the next release

**Comment by friendodevil** [comment]
Thank you

**Comment by arthur-morgan-1** [comment]
has live stream support ever added?

**Comment by alco28** [comment]
> has live stream support ever added?

show_live_stream: true as stated in the documentation
