### ISSUE TITLE
Configurable number of decimals to display

### ISSUE THREAD

**Issue by ahd71** [custom-cards/button-card#278]
In some cases it is not required/attractive to show all decimals from a sensor value in a dashboard (but still retain them in the sensor for other purposes).

Suggestion: Configuration parameter, i.e "Decimals: 2" (Like https://github.com/kalkih/mini-graph-card)

**Comment by iantrich** [comment]
I think it would be more prudent to do this on the backend via a template sensor rather than every card having to add configurations for this.

**Comment by RomRider** [comment]
You can already do that using templates if needed, I'm going to close this.

**Comment by guevara777** [comment]
It works like a charm with templates. Here´s my solution for everone who needs it:

```
   [...]
    variables:
      decimals: 2 # Number of decimals to round to and to display
      show_units: true # Do you want the unit of measerement to be visible in the state?
    state_display: |
      [[[
        var rounded_state = (Math.round(entity.state * 100)/100).toFixed(variables.decimals)
        var units = entity.attributes.unit_of_measurement
        if (variables.show_units == true)
          return rounded_state + " " + units;
        return rounded_state;
      ]]]
```
