### ISSUE TITLE
templates (java script) not working in variables 

### ISSUE THREAD

**Issue by rgogada** [custom-cards/button-card#281]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**
templates (java script) not working in variables 

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```yaml
variables:
      var1: >
        [[[ 
          if (Math.round((new Date() - new Date(entity.last_changed))  / 60000) < 60)
            return Math.round((new Date() - new Date(entity.last_changed)) / 60000);
          else if (Math.round((new Date() - new Date(entity.last_changed)) / 3600000) < 24) 
            return Math.round((new Date() - new Date(entity.last_changed)) / 3600000);
          else if (Math.round((new Date() - new Date(entity.last_changed)) / 86400000) < 30)
            return Math.round((new Date() - new Date(entity.last_changed)) / 86400000);
          else 
            return Math.round((new Date() - new Date(entity.last_changed)) / 2592000000);
        ]]]
```

**Screenshots**

**Expected behavior**
expected the java script value assigned to the variable. But the whole scripts is being assigned as a text

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
Variables (for now) do not support javascript. It's only static text. Why can't you just use that code directly wherever you need it?

**Comment by dwainscheeren** [comment]
Please reopen this and make it work, so we can use templating inside variables :)

**Comment by dwainscheeren** [comment]
Thanks :D
