### ISSUE TITLE
button does not fit on mobile screen

### ISSUE THREAD

**Issue by iptvcld** [custom-cards/button-card#282]
button does not fit on mobile screen when i set a style of height and width.
- I have 5 buttons in a row and on a mobile screen the 5th is cut off, it does not auto fit
styles:
        card:
          - height: 60px
          - width: 60px

**Comment by iantrich** [comment]
You set the width to 60px , I.e. the width will be 60px...

**Comment by iptvcld** [comment]
yea; figure that one out just now as well - used aspect ratio 1/1 and worked ok
