### ISSUE TITLE
Allow templates to resolve document elements

### ISSUE THREAD

**Issue by Petro31** [custom-cards/button-card#283]
**Is your feature request related to a problem? Please describe.**
I'd like to use hui-timestamp-display as a returned object to the label field.  When I return the element, it just renders: [object HTMLElement].

When I try and turn that into html using
```
html`${element}`
```
it renders [object Object]

If i try to create the HTML by hand....

```
return `
<hui-timestamp-display
  hass=${hass}
  ts=${date}
  format="relative";>
</hui-timestamp-display>
`
```

It 'works' but hass, ts, and format are all strings, making all references to them in hui-timestamp-display.ts cause unhandled exceptions.

**Describe the solution you'd like**
I'd like any [object HTMLElement] to be handled.  It would open so many new paths for the button card.

**Describe alternatives you've considered**
Currently, I just calculate the ts by hand... it works but it doesn't update every second like hui-timestamp-display does.  It updates in chunks.

```
  [[[
    var test = "{{ test }}";
    var ts_entity = states[test];
    if (ts_entity === undefined)
      return 'Invalid Entity';

    let now = new Date();
    let date = new Date(ts_entity.state);

    var tdelta = Math.floor((now - date)/1000);

    function plural(descriptor, divisor){
      var ret = Math.floor(tdelta/divisor);
      return (ret == 1) ? `${ret} ${descriptor} ago` : `${ret} ${descriptor}s ago`;
    }

    if (tdelta < 60)
      return plural('second', 1);
    else if (tdelta < 60 * 60)
      return plural('minute', 60);
    else if (tdelta < 60 * 60 * 24)
      return plural('hour', 60 * 60);
    else
      return plural('day', 60 * 60 * 24);
  ]]]
```

**Comment by RomRider** [comment]
Should be fixed in the next release

**Comment by Petro31** [comment]
@RomRider Awesome.  This will really take this card far IMO.  Whenever it gets released, I run a few tests.

**Comment by pansjk** [comment]
[[[
          var t = entity.last_changed;
          var tt = new Date(t);
          var ti = new Date();  
          var mms = ti-tt;
          var lab = ' ';
          var header = 'NULL';
           if ( mms > 999) {
              var days = parseInt(mms / (1000 * 60 * 60 * 24));
              var hours = parseInt((mms % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
              var minutes = parseInt((mms % (1000 * 60 * 60)) / (1000 * 60));
               
              if ( entity.state == 'off' ){
                 header = 'Malfunction ： ';
              }else if ( entity.state == 'on'  ){
                 header = 'Normal： ';
              }else {
                 header = 'NULL';
              }
              if ( days> 0){
                 header = header + days + 'days';
              }
              if ( hours> 0){
                 header = header + hours + 'hours';
              }
              if ( minutes> 0){
                 header = header + minutes + 'minutes';
              }
              
              var second = parseInt((mms % (1000 * 60 )) / 1000 );
              lab = header + second + 'seconds';
            }   
          return lab;
        ]]]


Will work too.~~~

**Comment by RomRider** [comment]
No, this will not be updated automatically if you stay on the page it should stay static.
