### ISSUE TITLE
allow for alternating background images

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#287]
**Is your feature request related to a problem? Please describe.**

I can not have a single button show alternating images automatically.

**Describe the solution you'd like**
 Would love to be able to set a button with eg todays and tomorrows trash images, and have that alternate on the button

**Describe alternatives you've considered**

**Additional context**

please see community on this:

https://community.home-assistant.io/t/lovelace-button-card/65981/3113?u=mariusthvdb and below, linking to 
https://css-tricks.com/css-basics-using-multiple-backgrounds/
http://css3.bradshawenterprises.com/cfimg/#cfimg2

**Comment by RomRider** [comment]
Not sure I understand what you are trying to achieve here?
I understand you want to alternate the background, but based on what? Automatically every `x` seconds?

**Comment by Mariusthvdb** [comment]
Yes thanks. In my current case, based on the state of 2 sensors, and if both evaluate to true, show a relevant background-picture.

And yes, alternating would be automatic, so each few seconds would be just fine.

If tried some keyframe solutions but didn’t come close yet. An image rotator... well the options seem rather extensive checking CSS  examples on the Web. Couldn’t get them to work in the background or background-picture options on the button card though

**Comment by RomRider** [comment]
Is it something like which you want to achieve?
![Mar-15-2020 18-47-15](https://user-images.githubusercontent.com/21064206/76707194-7e45b000-66ed-11ea-8e64-f89685c02852.gif)

**Comment by Mariusthvdb** [comment]
Yes! Though this is way more beautiful than what I envisioned ;-)
