### ISSUE TITLE
wrap text on a button

### ISSUE THREAD

**Issue by reynos** [custom-cards/button-card#289]
Is there a way to have a (multi word) name wrap the text to a second line on a button? Or is this feature request?

**Comment by RomRider** [comment]
It is possible already, check this post: https://community.home-assistant.io/t/lovelace-button-card/65981/2879

**Comment by reynos** [comment]
Thanks, these options work for me.
Are all the style options documented somewhere? this https://github.com/custom-cards/button-card#styles seems incomplete.

**Comment by RomRider** [comment]
You can use any CSS attributes, the purpose of this card's documentation is not to explain how css works 🙂 But google will help you with that!
