### ISSUE TITLE
Style: width no longer recognized

### ISSUE THREAD

**Issue by wbilger** [custom-cards/button-card#29]
Before the latest HA update, I could set the css style 'width: 675px' to modify the width of a column or vertical stack. Since the last HA update, it no longer works, or recognizes that setting.

**Comment by kuuji** [comment]
I'll have a look. Thanks for reporting this @wbilger

**Comment by wbilger** [comment]
Thanks, very, very useful feature to be able to setup a nicer grid in lovelace, especially on wall mounted devices.

**Comment by pruchai** [comment]
any news on this? having same issue

**Comment by ohadbenita** [comment]
Have the same issue for font-size which isn't respected

**Comment by RomRider** [comment]
Can you let us know if it's still an issue with the latest version 0.1.x?

**Comment by wbilger** [comment]
I still cannot get it to work on the newest version.

**Comment by RomRider** [comment]
@wbilger can you show us your config please? It's hard to reproduce without context.
