### ISSUE TITLE
Problem with slider entity row

### ISSUE THREAD

**Issue by martinversluis** [custom-cards/button-card#297]
I can’t get the slider entity row nice in the button card
When i set full row to true, the slider knob is placed at the right side of the button and i can not operate it
I folowed the example, what am i doing wrong?
Kind regards

![full row true](https://user-images.githubusercontent.com/60968980/76769641-033bd280-679d-11ea-9ca2-cef63c3e6e93.JPG)
![full row false](https://user-images.githubusercontent.com/60968980/76769707-151d7580-679d-11ea-8d23-ee1af7270386.JPG)

**Comment by RomRider** [comment]
You have to update the position of your element in the grid. Documentation is [here](https://github.com/custom-cards/button-card/blob/master/README.md#custom-fields)

Else this should do the trick for your use case (add it to your card config):
```yaml
styles:
  grid:
    - grid-template-areas: "i" "n" "s" "l" "slider"
    - grid-template-columns: 1fr
    - grid-template-rows: 1fr min-content min-content min-content min-content

**Comment by martinversluis** [comment]
Thank you very much this worked i had to put two extra apostrophe in the grid template area and now it looks great.
-
![custom button good](https://user-images.githubusercontent.com/60968980/76775245-5c0f6900-67a5-11ea-989d-b0f189a69845.JPG)

**Comment by poldim** [comment]
It would be helpful if you pasted your yaml config instead of pasting images of your yaml config.  Then it's search engine and copy friendly
