### ISSUE TITLE
Lock function not working after 3.2.1 update

### ISSUE THREAD

**Issue by tomerbs** [custom-cards/button-card#298]
Hi,
After updating to the latest 3.2.1 version the lock function is not working,
going back to version 3.2.0 solved the problem.

**Comment by RomRider** [comment]
"Not working" doesn't mean much. Could you please describe what is happening and share your configuration?

**Comment by tomerbs** [comment]
Hi,
Sorry for the missing info, i'm using decluttering-card with the lock
function and it's disappeared in version 3.2.1
I can confirm  version 3.2.2 fix the problem.
Thanks a lot.
