### ISSUE TITLE
Set own icon

### ISSUE THREAD

**Issue by claudioita** [custom-cards/button-card#3]
Some mdi:icon are not working, like 
kitchen 
monitor-dashboard

both present in the mdi website .. or maybe I am wrong?

**Comment by claudioita** [comment]
Also possible to use favicon?

**Comment by claudioita** [comment]
or maybe own icons? I find mdi lacking a lot of icons

**Comment by kuuji** [comment]
@claudioita thanks for the feedback. Someone suggested something similar on the home-assistant forum.

I'll add the ability to use a custom image in a future release.
