### ISSUE TITLE
Can we have the entity icon color customize template?

### ISSUE THREAD

**Issue by horacecar** [custom-cards/button-card#300]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The entity icon color customize template support

**Additional context**
I wanna to customize the mdi icon color depends on the state of a entity.

for example when the dimming light color is rgb(255,255,255) then show black color. Because the button card background is white , when the color of the light is red 
![1](https://user-images.githubusercontent.com/44496483/76881653-6d936680-68b4-11ea-8a71-f23cafb320e6.png)
when the color of the light is blue
![2](https://user-images.githubusercontent.com/44496483/76881678-76843800-68b4-11ea-97e4-6422dab719ce.png)
but if the color is white, it show nothing on the card.
![3](https://user-images.githubusercontent.com/44496483/76881708-856aea80-68b4-11ea-9ed4-7b1eb1d15603.png)
once we can template the icon color, then i can set it to when the light's rgb(255,255,255) will show normal yellow of black color , otherwise, there's nothing on the card only the name

**Comment by RomRider** [comment]
You can already do that with state templates:
```
state:
  - operator: template
    value: '[[[ your test here]]]'
    styles:
      icon:
        - color: black
```

**Comment by horacecar** [comment]
@RomRider 

Hello RomRider, i tried few hours but still cannot success, the below is my config. All i wanna do is wanna the light to show black color when the rgb light's color is (255,255,255) to prevent the icon disappear on the card (because the background of the card and the icon is white)

`cards:
  - entity: light.gateway_light
    name: Test Light
    layout: name_state
    show_name: true
    show_state: false
    state:
      - operator: default
        icon: 'mdi:spotlight'
        styles:
          icon:
            - color: >
                  [[[
                    if ((states['light.gateway_light'].attributes.rgb_color[0] == '255')&&             (states['light.gateway_light'].attributes.rgb_color[1] == '255')&&   (states['light.gateway_light'].attributes.rgb_color[2] == '255'))
                      return "black";
                    return "auto";
                  ]]]
    styles:
      card:
        - font-size: 12px
        - font-weight: bold
    tap_action:
      action: toggle
    type: 'custom:button-card'
type: horizontal-stack
`

![TEST](https://user-images.githubusercontent.com/44496483/76947120-1aff8c00-6940-11ea-809c-ff7961638f34.png)

**Comment by RomRider** [comment]
Try this below:
```
cards:
  - entity: light.gateway_light
    name: Test Light
    layout: name_state
    show_name: true
    show_state: false
    icon: 'mdi:spotlight'
    color: >
      [[[
        if (states['light.gateway_light'].attributes.rgb_color &&
        (states['light.gateway_light'].attributes.rgb_color[0] == 255) &&            
        (states['light.gateway_light'].attributes.rgb_color[1] == 255) &&
        (states['light.gateway_light'].attributes.rgb_color[2] == 255))
          return "black";
        return "auto";
      ]]]
    styles:
        card:
          - font-size: 12px
          - font-weight: bold
    tap_action:
        action: toggle
    type: 'custom:button-card'
type: horizontal-stack
```

**Comment by horacecar** [comment]
@RomRider Thank you for the reply. Your scrip i already tried, but still cannot, I try another easier, for example

 if (states['light.door_light'].state === 'on' )

also still cannot.

**Comment by RomRider** [comment]
Are you sure you are using the correct version of button-card? What is the javascript console saying?

**Comment by horacecar** [comment]
@RomRider  Hello, yes, iam sure, i am using the latest version of button-card. 
may be color cannot suport template???

> 
Those are the configuration fields which support templating:

name (Supports also HTML rendering): This needs to return a string or an html`<elt></elt>` object
state_display (Supports also HTML rendering): This needs to return a string or an html`<elt></elt>` object
label (Supports also HTML rendering): This needs to return a string or an html`<elt></elt>` object
entity_picture: This needs to return a path to a file or a url as a string.
icon: This needs to return a string in the format mdi:icon
All the styles in the style object: This needs to return a string
All the value of the state object, appart when the operator is regex
operator: template: The function for value needs to return a boolean
Else: The function for value needs to return a string or a number
All the custom_fields (Support also HTML rendering): This needs to return a string or an html`<elt></elt>` object
All the styles: Each entry needs to return a string (See here for some examples)
The extra_styles field
Everything field in *_action
The confirmation text (confirmation.text)
The lock being enabled or not (lock.enabled)
all the card parameters in a custom_field
all the variables
Inside the javascript code, you'll have access to those variables:

entity: The current entity object, if the entity is defined in the card
states: An object with all the states of all the entities (equivalent to hass.states)
user: The user object (equivalent to hass.user)
hass: The complete hass object
variables: an object containing all your variables defined in the configuration. See Variables
>

**Comment by jazzyisj** [comment]
The code below is working code pulled right from my config that changes both the icon and the icon color with a template.  This is not an issue with this card.  The capability to do what you want is already there and working.  The forums is probably  better place to ask questions like this.

```
      - type: custom:button-card
        template: menu_button
        entity: alarm_control_panel.house
        name: Alarm
        icon: >
          [[[
            if (states['sensor.house_alarm_status'].state == 'Disabled')
              return 'mdi:shield-remove';
            else if (states['alarm_control_panel.house'].state == 'disarmed')
              return 'mdi:shield-check';
            else if (states['alarm_control_panel.house'].state == 'armed_home')
              return 'mdi:shield-home';
            else if (states['alarm_control_panel.house'].state == 'armed_night')
              return 'mdi:shield-star';
            else if (states['alarm_control_panel.house'].state == 'armed_away')
              return 'mdi:shield-lock';
            else if (states['alarm_control_panel.house'].state == 'pending')
              return 'mdi:shield-half-full';
            else if (states['alarm_control_panel.house'].state == 'warning')
              return 'mdi:shield-alert-outline';
            else
              return 'mdi:alert';
          ]]]
        styles:
          icon:
            - color: >
                [[[
                  if (states['sensor.house_alarm_status'].state == 'Disabled')
                    return 'var(--disabled-text-color)';
                  else if (states['alarm_control_panel.house'].state == 'disarmed')
                    return 'var(--alarm-disarmed-color)';
                  else if (states['alarm_control_panel.house'].state == 'armed_home')
                    return 'var(--alarm-armed-home-color)';
                  else if (states['alarm_control_panel.house'].state == 'armed_night')
                    return 'var(--alarm-armed-night-color)';
                  else if (states['alarm_control_panel.house'].state == 'armed_away')
                    return 'var(--alarm-armed-away-color)';
                  else if (states['alarm_control_panel.house'].state == 'pending')
                    return 'var(--alarm-pending-color)';
                  else if (states['alarm_control_panel.house'].state == 'warning')
                    return 'var(--alarm-warning-color)';
                  else
                    return 'var(--entity-warning-color)';
                ]]]
```

**Comment by RomRider** [comment]
I think the question has been answered, closing
