### ISSUE TITLE
Support for CSS pseudo elements (::before, ::after)

### ISSUE THREAD

**Issue by libots** [custom-cards/button-card#308]
**Is your feature request related to a problem? Please describe.**
Not a problem, but it would be very useful.

**Describe the solution you'd like**
I would like to be able to define ::before and ::after for things like custom fields. In my use case, I have a battery value reported for the field. This can be a string (high/medium/low) or integer, depending on the device. Since I'm using the value in scripts, I can't just prepend a battery icon in the field, but I'd like to display one. CSS ::before would be perfect for this.

**Describe alternatives you've considered**
None that come to mind.

**Additional context**
None.

**Comment by RomRider** [comment]
Maybe I don't understand your point (might be easier with a config) but you can display any HTML element in custom_fields (see the examples in the documentation).

**Comment by RomRider** [comment]
Also you can probably use `extra_styles` to inject the CSS you want. The `id` of the element will be the name of the `custom_field` in your config.
```
extra_styles: |
  #CUSTOM_ELEMENT_NAME::before {
    content: "Read this: ";
  }

**Comment by RomRider** [comment]
@libots, any update with this? Can I close the issue?

**Comment by RomRider** [comment]
No update, closing
