### ISSUE TITLE
Button-card template 'remote_button_round' is missing!

### ISSUE THREAD

**Issue by magostinelli** [custom-cards/button-card#320]
With the last version. i have this error:
Button-card template 'remote_button_round' is missing!

Inside my configuration I have:
template: remote_button_round

**Comment by RomRider** [comment]
And this template doesn't exist in `button_card_templates` that's why you have this error.

**Comment by magostinelli** [comment]
But I obtained the error after updating button, card. In this case, I don't know, where i found it! :-)

**Comment by RomRider** [comment]
Yes because before I didn't check if the template existed or not. That's not a bug.
Either remove this line or create a template with this name. If you don't know what it is, you can probably remove it.

**Comment by RomRider** [comment]
Any update, can I close this?

**Comment by magostinelli** [comment]
I switched to other template, so I close the issue.
