### ISSUE TITLE
how to get rid of the defautl white shadow border around the component?

### ISSUE THREAD

**Issue by DanielPiccoli** [custom-cards/button-card#326]
Is there a way to get rid of the white shadow border the component adds by default ?

![image](https://user-images.githubusercontent.com/13155817/82346165-814e6c80-99cc-11ea-88e6-dae5a632601b.png)

here is a small corner of the button on a darker background - how do i change this ?

**Comment by RomRider** [comment]
That's the box-shadow of your theme, nothing related to button-card, but if you want to get rid of it, you can just do:
```yaml
styles:
  card:
    - box-shadow: none
```

**Comment by RomRider** [comment]
Going to close this as it seems resolved.
