### ISSUE TITLE
Is it possible to store and reuse JS template between card instances?

### ISSUE THREAD

**Issue by alesquire** [custom-cards/button-card#327]
I have a dozen oа cards that displays duration- how long particular binary sensor is in it's current state. And  I have to copy-paste all this stuff several tiles. Is it possible to extract card template  or even a JS function template, so I could pass sensor name as input parameter to function and get a result. 

          label: >
            [[[
              var sensorName= 'binary_sensor.mysensor' 
              var currentDate = Date.now();
              var changeDate = new Date(states[sensorName].last_changed);  
              var duration= Math.trunc((currentDate - changeDate.getTime())/1000);
              var seconds = duration%60;
              var minutes = (Math.trunc(duration/60))%60;
              var hours = (Math.trunc(duration/3600))%24;
              var days =  Math.trunc(duration/86400);
              var text= 
                  ((days>0)?(days +'дн '):'')+
                  ((days<10 && hours>0)?(hours +'ч '):'')+
                  ((days==0 && hours<6 && minutes>0)?(minutes +'м '):'')+
                  ((days==0 && hours==0 && minutes<15 && seconds>0)?(seconds +'с '):'');
              return text;
            ]]]

**Comment by matt8707** [comment]
`button_card_templates:` and don't specifically define you entity.
```
var sensorName = entity.entity_id
```

If you want a sensor other than the current entity, name them the same and replace the domain.

```
entity.entity_id.replace('switch', 'sensor')
```

**Comment by alesquire** [comment]
Thanks, matt8707 

That's exactly what I've expected!
