### ISSUE TITLE
No icons when using javascript templates

### ISSUE THREAD

**Issue by shauder** [custom-cards/button-card#329]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
I am not seeing any icons in my buttons when I am setting the icons dynamically with javascript templates. This all worked before upgrading to the latest version of Home Assistant. I am using Font Awesome icons. I checked the breaking changes and didn't see anything that would relate to this.

**Version of the card**
Version: 
3.3.5

**To Reproduce**
This is the configuration I used:

```yaml
icon: >
  [[[
    if (entity.entity_id.startsWith('light') && entity.entity_id.indexOf('doorway') > -1)
    {
      if (entity.state == "on")
      {
        return "fad:light-ceiling";
      }
      else
      {
        return "far:light-ceiling";
      }
    }
    else if (entity.entity_id.startsWith("light") && entity.entity_id.indexOf('lamps') > -1)
    {
      if (entity.state == "on")
      {
        return "fad:lamp";
      }
      else
      {
        return "far:lamp";
      }
    }
  }}}
```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
Chrome, Safari, FireFox
Latest versions

**Smartphone (please complete the following information):**
iPhone 11 Pro
13.5
safari and mobile app
latest versions

**Additional context**

**Comment by RomRider** [comment]
This is unrelated to button card. Font awesome doesn't work with 0.110 unless you use the master branch of the font awesome repo where it is already fixed, but not released.

**Comment by shauder** [comment]
Thanks I will check it out!
