### ISSUE TITLE
Button Card not working in Chrome anymore

### ISSUE THREAD

**Issue by DanielOrneling** [custom-cards/button-card#330]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
The button card works perfectly in the Android HomeAssistant app, but not in Chrome. I´ve tried installing an earlier version of button card, clearing cache, rebooting HA and have reproduced the issue on both my cell phone and computer. Just says Custom element doesn't exist: button-card.

**Version of the card**
Version: 3.3.5

**Version of HA**
0.110.1

**To Reproduce**
I´m using HACS

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [Chrome]
 - Version 83.0.4103.61 (Computer), 81.0.4044.138 (Android)

**Comment by RomRider** [comment]
It works for everyone but you so your configuration is probably not correct :wink:
How did you declare the resource and in which file?

**Comment by DanielOrneling** [comment]
> It works for everyone but you so your configuration is probably not correct 😉
> How did you declare the resource and in which file?

Most likely yes :)

It´s defined in Configuration->Lovelace Dashboards->Resources as a JavaScript Module with the URL /community/button-card/button-card.js

The funky thing is that it works in the HA app for Android, but not on Chrome desktop.

**Comment by RomRider** [comment]
With HACS the path to resources starts with `/hacsfiles` not `/community`

**Comment by DanielOrneling** [comment]
> With HACS the path to resources starts with `/hacsfiles` not `/community`

Thanks, that was it! No issues with button card on other words :)
