### ISSUE TITLE
after updating to Home Assistant 0.110.5 size settings stopped working

### ISSUE THREAD

**Issue by daboshman** [custom-cards/button-card#339]
hi
this is my code:
![image](https://user-images.githubusercontent.com/48977190/83951491-65572180-a83a-11ea-9f35-0644c3472eee.png)

and i am with the latest version of the add on also (using hacs)

**Comment by RomRider** [comment]
Width and height are not defined like this and never have been. Please read the [documentation](https://github.com/custom-cards/button-card/blob/master/README.md).
This is how you set width and height in button-card:
```yaml
styles:
  card:
    - width: 700px
    - height: 700px
```

Also `default_color` doesn't exist as a configuration property and `action` doesn't exist either.
