### ISSUE TITLE
Action list for tap, hold...

### ISSUE THREAD

**Issue by urbatecte** [custom-cards/button-card#345]
**Is your feature request related to a problem? Please describe.**
I'd like to perform several actions when tap_action without writing a script.

**Describe the solution you'd like**
tap_action:
  action: call-service
  service: remote.turn_off
  service_data:
    entity_id: remote.salon
  service: media_player.turn_off
  service_data:
    entity_id: media_player.salon

**Describe alternatives you've considered**
Writing dedicated scripts for each action type, but it's for a remote card with plenty of button.
Playing with template. As I'm a noob I failed ! If it's the right way, may someone reply with a exemple ;o)

**Comment by iantrich** [comment]
Why are you against using a script? That is the ideal/proven solution rather than putting the onerous on the frontend.

**Comment by RomRider** [comment]
Frontend is not supposed to handle automation logic so scripts are the way to go here.

**Comment by carloda** [comment]
Is there an alternative solution? a script cannot invoke an app " action: url
  url_path: app://com.ajaxsystems" so I cannot insert this call either into a script or into an automation

**Comment by ngocjohn** [comment]
@carloda Are you using android? Or ios? In ios you can create a shortcut to launch the app... In ha app works normally via tap action. Like this. 
```
unifi_ios:
  tap_action:
    action: url
    url_path: shortcuts://run-shortcut?name=Open Unifi
```

**Comment by carloda** [comment]
> @carloda Are you using android? Or ios? In ios you can create a shortcut to launch the app... In ha app works normally via tap action. Like this.
> 
> ```
> unifi_ios:
>   tap_action:
>     action: url
>     url_path: shortcuts://run-shortcut?name=Open Unifi
> ```

I use Android, I would like a tap_action to first run a script and then open an app. Thanks
