### ISSUE TITLE
Feature request: Multiple Services on Action

### ISSUE THREAD

**Issue by emouawad** [custom-cards/button-card#359]
Not sure if this is already possible but what i would like to do is being able to call more than one service on tap_action for example.
So instead of just calling 1 service with it's service data - to be able to call multiple services each with it's own service_data naturally.

Something like:

type: "custom:button-card"
tap_action:
      - action: call-service
        service: service1
        service_data:

      - action: call-service
        service: service2
        service_data:

**Comment by RomRider** [comment]
You should use a script for that and then call the script from the button.

Duplicate of #345

**Comment by emouawad** [comment]
Oh thanks for the fast reply 😃 
Makes sense will do as suggested - was thinking definitely there is surely a way for that! 😉
