### ISSUE TITLE
Timers on buttons stop updating when page loses focus

### ISSUE THREAD

**Issue by kloggy** [custom-cards/button-card#365]
**Checklist**
- [ x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
As the title says.
A button based on a timer stops counting down if the page loses focus. I have done some testing and this appears not to be the case with the core button card

**Version of the card**
Version: 3.3.6

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser Microsoft Edge (Chromium)

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by RomRider** [comment]
Fixed in `3.3.7-0` (you need to display beta version in HACS)

**Comment by asifma** [comment]
Thanks, this also solved my issues 👍
