### ISSUE TITLE
Embed another card in a button card 

### ISSUE THREAD

**Issue by thib5** [custom-cards/button-card#370]
Hi, This card is really cool and really well done so some time I would like to have options of custom button card on other card.. If I remember right I already embed another card into a button card but I can't remember how 

can you tell me if it's possible and how.

Thanks

**Comment by jaburges** [comment]
Click [here](https://github.com/custom-cards/button-card#custom-fields) Scroll down to the graph card example

**Comment by RomRider** [comment]
I'm closing this as it has been answered by @jaburges. Thanks.
