### ISSUE TITLE
Image (icon) with smaller mdi icon in corner

### ISSUE THREAD

**Issue by jaburges** [custom-cards/button-card#371]
**Is your feature request related to a problem? Please describe.**
I would like to show an icon to depict the specific entity. 
I would then like to show a mdi icon like a green check mark or red X to show the state in the corner of the button card

**Describe the solution you'd like**
icon like the image of a docker container, then top right overlaid (like iOS or Android apps telling you how many notifications you have) would be the 'state' of the container.

**Describe alternatives you've considered**
Errrrm - tried making it using the custom button card, but sadly can not figure out how to add more than one image successfully

**Additional context**
Thanks for your work, this must be THE most used Lovelace card!

**Comment by NovaGL** [comment]
Look at the custom fields example its similar
https://github.com/custom-cards/button-card#custom-fields

**Comment by jaburges** [comment]
> Look at the custom fields example its similar
> https://github.com/custom-cards/button-card#custom-fields

Thanks - issue is I cant figure out how to use an icon (like a logo.jpg) instead of the `icon:mdi-blah`

**Comment by NovaGL** [comment]
You have to use entity-picture instead

**Comment by jaburges** [comment]
ah-ha! ok thank you

**Comment by RomRider** [comment]
You can use the `<img>` tag to display your image. Check [here](https://www.w3schools.com/tags/tag_img.asp)
