### ISSUE TITLE
Icon Color behavior

### ISSUE THREAD

**Issue by jimz011** [custom-cards/button-card#376]
**Is your feature request related to a problem? Please describe.**
When an entity has both rgb as well as color temperature the icon color does show up as white (and not as the temperature-color)

**Describe the solution you'd like**
When the entity attribute `hs_color: 0, 0` and attribute `color_temperature` exists, then show the current temperature as the color of the entity (like it would do with lights that solely have color_temperature).

**Describe alternatives you've considered**
I could break up the light into two components (one being the rgb and one being the color-temperature). Though this would not really serve my needs.

**Additional context**
It works fine with rgb and it works fine with color-temperature, though it doesn't know what to do when the entity has both. I hope you can add something like this.

**Comment by RomRider** [comment]
Could you share the full state from the dev panel of this entity and what you'd expect to happen in this exact state?
Do you want to ignore the RGB and just have the temperature shown?

**Comment by jimz011** [comment]
Oh, I only come to see this response now! But it seems that this is only the case when mixing white value with color. Since my strips didn't work fine like that anyways I've now disabled the white leds when rgb is on and vice versa. This is no longer an issue so I will close this. Sorry to have bothered you!
