### ISSUE TITLE
0.116 Breaking Changes

### ISSUE THREAD

**Issue by homecb** [custom-cards/button-card#380]
Beginning HA 0.116 all custom Lovelace cards (at least those that I use), including this one, no longer work.

The 0.116 release notes included a link to a [blog post](https://developers.home-assistant.io/blog/2020/10/02/lazymoreinfo/) explaining the (breaking) changes.

I do not consider this as a bug per se, but was wondering what the developer's plans are regarding this matter. I ask in light of the [recent announcement](https://community.home-assistant.io/t/custom-header/155399/1100) that the developer of Custom Header has decided to stop working on the project.

Thanks tot the dev for your work.

**Comment by DickSwart** [comment]
+1

**Comment by RomRider** [comment]
I don't see why button-card wouldn't work on 0.116 since I'm not using any more-info component.
What issue do you have?

**Comment by homecb** [comment]
After a dramatic initial post I now I feel like a complete idiot.

I tried upgrading again (this time to 0.116.1 after reverting to 0.115.6)  and everything works fine. My upgrade to 0.116 which I tested twice both produced the same results - `custom element does not exist`.

Apologies for the trouble and thanks again for your work.

Closing the ticket.
