### ISSUE TITLE
Get current view name in JS template

### ISSUE THREAD

**Issue by andreypolyak** [custom-cards/button-card#383]
**Is your feature request related to a problem? Please describe.**
I’m using horizontal-stack of buttons instead of HA header to navigate across different views in Lovelace. It’s more configurable and I have more control over it. Today I need to add this stack with buttons to all views and change selected button (so it will be displayed in Lovelace as selected view) for each view manually in the YAML. I want to have the same code with stack of buttons on all views and have buttons selected by JS template (something like if current view is “kitchen” than set this button state as selected). I was not able to find view name variable (or at least url of current page) in documentation, so I assume it’s not supported yet.

**Describe the solution you'd like**
Add variable with current view name to JS templates.

**Describe alternatives you've considered**

**Additional context**

**Comment by Mariusthvdb** [comment]
sure that's possible, check https://community.home-assistant.io/t/lovelace-button-card/65981/4649?u=mariusthvdb

```
window.location.pathname
```
is the magic word in JS

**Comment by andreypolyak** [comment]
@Mariusthvdb, thank you very much! It works as expected.
