### ISSUE TITLE
No dynamic styling with browser_mod popup 

### ISSUE THREAD

**Issue by MaartenMees** [custom-cards/button-card#397]
My Home Assistant version: 17.XX.X

What I am doing:

I made a browser_mod popup with buttons. If you push button should change color.

What happened instead:

Buttons keep color. Unless you reopen the popup.

This

![Screenshot_20201109-124459_Home Assistant](https://user-images.githubusercontent.com/26173684/98565562-08124100-22ae-11eb-8ec4-a9d7eae7629a.jpg)

Shoud be this after pushing "Aan". But only happens after reopening..

![Screenshot_20201109-124442_Home Assistant](https://user-images.githubusercontent.com/26173684/98565617-17918a00-22ae-11eb-818f-e0825d4b0006.jpg)

Any ideas somebody? Works fine without popup. I use custom:button-card for the buttons.

Thanks!

**Comment by RomRider** [comment]
This is unrelated to button-card. Please open an issue in browser_mod's repo.

Button card will only update if it receives the update from the pop-up, if it's not receiving anything, it will not update. It's not something I have control over.

**Comment by MaartenMees** [comment]
Hi, thanks for the fast response! I did open an issue there.. and someone suggested it may be a problem with the button card. Thats why I posted it here also. Thanks

**Comment by MaartenMees** [comment]
My bad. Was using styles from custom:button-card
When using card-mod everything works as expected.
