### ISSUE TITLE
Javascript in url_path

### ISSUE THREAD

**Issue by daranto** [custom-cards/button-card#400]
Hello,

it would be great if javascript templates would work in url_path. 

For example, the following works in the name but not in the URL:
```
name: '[[[ var seconds = new Date().getTime() / 1000; return seconds ]]]'

URL: https://URL/recording.mov?='[[[ var seconds = new Date().getTime() / 1000; return seconds ]]]'
```

Thanks a lot in advance.

Daranto

**Comment by RomRider** [comment]
It works in the `url_path` however, your configuration is wrong :)

`` url_path: '[[[ var seconds = new Date().getTime() / 1000; return `https://URL/recording.mov?=${seconds}` ]]]' ``

**Comment by daranto** [comment]
Yeah. Thanks for your help 👍. I am not really familiar with Javascript.
