### ISSUE TITLE
No card type configured error

### ISSUE THREAD

**Issue by thouters** [custom-cards/button-card#401]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
I can't use the button card.
I get the following error:

No card type configured.

- type: 'custom:button-card'
  color_type: blank-card

I ran wget to place the file in /usr/share/hassio/homeassistant/www:
wget http://www.github.com/custom-cards/button-card/releases/latest/download/button-card.js

I added "/local/button-card.js" using the dashboard resources GUI http://hass/config/lovelace/resources

I then tried to use the card in a new dashboard.

I don't have any leads to troubleshoot the issue:
- how can I check the javascript is successfully registered? (web inspector makes me no wiser) (i tried adding typo's to the filename and home assistant gives not error)
- how can I check the javascript resource is available to the frontend?
- Why does the README.md mention nothing about using the GUI for everything (registering the resource, adding it to a dashboard)?
**Version of the card**
Version: latest (14 nov 2020) and 3.3.6

**To Reproduce**
This is the configuration I used:
```yaml
title: living
views:
  - title: ''
    icon: 'mdi:sofa'
    theme: happy
    badges: []
    cards:
      - type: 'custom:button-card'
        color_type: blank-card
```

**Screenshots**
![buttoncard](https://user-images.githubusercontent.com/185604/99222720-6d50bf80-27e3-11eb-8664-4881b800672c.png)

**Expected behavior**
I expected to be able to use the button card

**Desktop (please complete the following information):**
 - Browser chrome, firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
Did you reload the resources or restart your home assistant? Did you add it as a module?

There's no documentation because adding a card through the GUI is documented in homeassistant's documentation.

**Comment by thouters** [comment]
Hi @RomRider, I tried restarting HA, clearing browser cache, trying chrome instead.
I made a screenshot yesterday but didn't have enough time to attach it. I think the javascript gets loaded since a message is printed. I'll try attaching the screenshot

**Comment by RomRider** [comment]
From what I can see in the screenshot, the config loads your array of cards as one unique card, so that is why you are having issues.
Your formatting/indentation seems to be wrong.

**Comment by thouters** [comment]
Hi, I indeed had a yaml issue, there was an extra '-' like:
cards:
 -   - type:
I suspect I need glasses. Sorry to bother, thanks for the feedback!
