### ISSUE TITLE
Get attributes status ?

### ISSUE THREAD

**Issue by m4dm4rtig4n** [custom-cards/button-card#402]
Hello,

I can't customize the status of my button according to an attribute of my main entity.

Currently, here is what I defined in my lovelace:
```
                  - type: "custom:button-card"
                    entity: sensor.59_weather_alert
                    icon: mdi:weather-sunny-alert
                    size: 65px
                    show_state: true
                    show_name: false
                    state:
                      - operator: template
                        value: >
                          [[[
                              return states["sensor.59_weather_alert"].attributes['Canicule']
                          ]]]
                    styles:
                      card:
                        - height: 87px
                      icon:
                        - color: >
                            [[[
                              if (entity.state == "Vert") return "var(--paper-item-icon-color)";
                              if (entity.state == "Jaune") return "#F1C40F";
                              if (entity.state == "Orange") return "#E67E22";
                              if (entity.state == "Rouge") return "#E74C3C";
                              return "#CBCBCB";
                            ]]]
```

The displayed status always remains that of the main sensor `sensor.59_weather_alert`

Do you have an idea ?

Thx

**Comment by RomRider** [comment]
You have the `state_display` config parameter which supports javascript templates and it will replace the state when used. This way you can do things like:
state_display: [[[ return entity.attributes.other_state ]]]'

**Comment by m4dm4rtig4n** [comment]
Thx for your help @RomRider 

I also tested this, but the attribute status does not go up as well: /

```
                  - type: "custom:button-card"
                    entity: sensor.59_weather_alert
                    icon: mdi:weather-sunny-alert
                    size: 65px
                    show_state: true
                    show_name: false
                    state_display: "[[[ return entity.attributes['Canicule'] ]]]"
                    styles:
                      card:
                        - height: 87px
                      icon:
                        - color: >
                            [[[
                              if (entity.state == "Vert") return "var(--paper-item-icon-color)";
                              if (entity.state == "Jaune") return "#F1C40F";
                              if (entity.state == "Orange") return "#E67E22";
                              if (entity.state == "Rouge") return "#E74C3C";
                              return "#CBCBCB";
                            ]]]
```

**Comment by RomRider** [comment]
What is displayed when you use this code?

Are you running the latest version? What is displayed in the javascript console for the button-card version?

Also are you sure you have an attribute which has a capital letter (`Canicule`) in your entity ? Can you share the full state of your entity from the dev panel in HA?

Also, better use this format also `entity.attributes.name` vs `entity.attributes['name']`

**Comment by m4dm4rtig4n** [comment]
I use v3.3.6, Chrome console :
![image](https://user-images.githubusercontent.com/7872518/99536294-7344cd00-29aa-11eb-929b-eb67a112403f.png)

The attributes go back correctly in the development console :
![image](https://user-images.githubusercontent.com/7872518/99536760-0f6ed400-29ab-11eb-9673-03fb8614fedd.png)

The problem now is that I have attributes with a dirty format ...
Style "Vent violant", "Neige-verglas", ...

So I have to define them this way: /

**Comment by RomRider** [comment]
Alright, you didn't answer this part: What is displayed when you use this code?

if `entity.attributes.Canicule` is empty, why do you expect it to show anything in button-card?

**Comment by m4dm4rtig4n** [comment]
> Alright, you didn't answer this part: What is displayed when you use this code?
It displays the value of the sensor (not the attribute)

It is to recover change the color of the icon according to the status :
* none = grey
* Vert = green
* Jaune = yellow
* Orange = orange
* Rouge = red

**Comment by RomRider** [comment]
I see why it's not displayed.
If the result is empty it will revert back to displaying the status, so what you can do is:
`state_display: '[[[ return entity.attributes.Canicule? entity.attributes.Canicule : ""; ]]]'`

**Comment by m4dm4rtig4n** [comment]
Thx for your help @RomRider , it's work :+1: 

```
                  - type: "custom:button-card"
                    entity: sensor.59_weather_alert
                    icon: mdi:weather-sunny-alert
                    size: 65px
                    show_state: false
                    show_name: false
                    styles:
                      card:
                        - height: 87px
                      icon:
                        - color: >
                            [[[
                              var status = entity.attributes['Canicule']? entity.attributes['Canicule'] : 'none';
                              if (status == "none") return "#9D9D9D";
                              if (status == "Vert") return "var(--paper-item-icon-color)";
                              if (status == "Jaune") return "#F1C40F";
                              if (status == "Orange") return "#E67E22";
                              if (status == "Rouge") return "#E74C3C";
                            ]]]
```

**Comment by RomRider** [comment]
Great 👍
