### ISSUE TITLE
Template support

### ISSUE THREAD

**Issue by oywino** [custom-cards/button-card#407]
I'm trying to get a simple template like this to work in your button-card:

```
service: '{{ "climate.turn_on" if is_state("sensor.av_pa", "Av") else "climate.turn_off" }}'
service_data:
  entity_id: climate.thermostat_5
```

The template works ok when I test it using the Developer Tools --> Template. It returns the correct service string depending on the sensor state. But as soon as I insert this into the button-card, I get the following error:

![image](https://user-images.githubusercontent.com/18447119/100937943-1db50800-34f4-11eb-8a07-56d302d643da.png)

Any idea what I'm doing wrong (I assume your button-card does support ordinary templating?)

**Comment by rccoleman** [comment]
That's not the proper formatting for templates in the button card.  Review the docs here: https://github.com/custom-cards/button-card#javascript-templates

**Comment by RomRider** [comment]
Button card supports javascript only, not jinja2.

**Comment by oywino** [comment]
That's interesting. And how would I write the above template using javascript ?
(I have spent a lot of time learning basic YAML - now is perhaps the time to learn javascript also?)

**Comment by RomRider** [comment]
Like this:
```
service: '[[[ return states['sensor.av_pa'].state === "Av" ? "climate.turn_on" : "climate.turn_off" ]]]'
service_data:
  entity_id: climate.thermostat_5
```

**Comment by oywino** [comment]
Nope - doesn't work:
`type: button
tap_action:
  action: call-service
  service: '[[[ return states['sensor.av_pa'].state === "Av" ? "climate.turn_on" : "climate.turn_off" ]]]'
  service_data:
    entity_id: climate.thermostat_5`

It gave this error:
`bad indentation of a mapping entry at line 4, column 103: ... e.turn_on" : "climate.turn_off" ]]]'`

**Comment by RomRider** [comment]
`type: button` is not button-card, please read the documentation.

**Comment by oywino** [comment]
Please explain? All I did was to use the GUI card creator, and this is what it gave me:
![image](https://user-images.githubusercontent.com/18447119/102949741-444dd980-44c9-11eb-9cdb-ed0b0e9bbcd6.png)

So, if `type: button` is not a button-card, then why does it say so?

**Comment by rccoleman** [comment]
> @RomRider, please explain? All I did was to use the GUI card creator, and this is what it gave me:

You’re confusing the built-in, less-functional button card with this *custom* button. Despite the similar names, they are completely different. If you want to use this card and its extended capabilities, you need to install and use it as per the instructions.

**Comment by oywino** [comment]
Aha, now I understand.  Thank you for pointing out the obvious 😮

**Comment by RomRider** [comment]
Initial issue seems answered, closing.
