### ISSUE TITLE
Show up in card picker

### ISSUE THREAD

**Issue by KTibow** [custom-cards/button-card#415]
**Is your feature request related to a problem? Please describe.**
You can make a custom card show up in the card picker. Button-card doesn't show up.

**Describe the solution you'd like**
Use this syntax to add to the card picker:
```
window.customCards = window.customCards || [];
window.customCards.push({
  type: "content-card-example",
  name: "Content Card",
  preview: false, // Optional - defaults to false
  description: "A custom card made by me!" // Optional
});
```

**Describe alternatives you've considered**
Don't do anything

**Additional context**

**Comment by RomRider** [comment]
Great, I didn't know that as I've never used anything else than lovelace in yaml mode 😅
Doesn't that also require to create an editor form of some sort to configure the card from the UI? (Which is something I'll never do because of the hundreds of options of button-card 😅)

**Comment by KTibow** [comment]
Nope. By default it won't specify any config, just the one `type` line.
