### ISSUE TITLE
accept entities icon_color attribute

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#419]
**Is your feature request related to a problem? Please describe.**

Using [custom_ui](https://github.com/Mariusthvdb/custom-ui), next to templating existing attributes, we can set (and template) an additional _icon_color_ attribute for an entity. 

per domain, per _glob, or per entity. Just like any other customization in HA.

regular entities card in HA respects that, as do many other cards in HA. More-info popup does.

Unfortunately, custom button-card does not.

<img width="557" alt="Schermafbeelding 2021-01-12 om 11 48 37" src="https://user-images.githubusercontent.com/33354141/104304836-30940280-54cc-11eb-8189-84a0c33bf9cf.png">

<img width="816" alt="Schermafbeelding 2021-01-12 om 11 49 37" src="https://user-images.githubusercontent.com/33354141/104304911-4bff0d80-54cc-11eb-9939-4ed255e42494.png">

**Describe the solution you'd like**

Next to the formatting options button-card does offer (which are huge and great, don't get me wrong, use them all over) it would be really nice if button-card could accept the icon_color attribute if available ( when set by custom_ui)

**Describe alternatives you've considered**

**Additional context**

set an icon and icon_color, based on the state of the entity. Icon is respected in button-card, unfortunately, icon_color isnt.

One huge advantage would be that the glob customizations we can set using custom_ui, would prevent all individual per entity styling in button cards.

eg check all that is necessary for my battery sensor coloring:
```
    sensor.*_bewegingssensor:
      templates: &battery_color
        icon_color: >
          if (state > 75) return 'green';
          if (state > 50) return 'gold';
          if (state > 25) return 'orange';
          if (state > 10) return 'brown';
          return 'red';

    sensor.*_dimmer:
      templates: *battery_color

    sensor.*_afstandsbediening:
      templates: *battery_color

    sensor.*_remote:
      templates: *battery_color

    sensor.*_battery_level:
      templates: *battery_color

    sensor.*_battery:
      templates: *battery_color

    sensor.battery*:
      templates: *battery_color
```
This makes the magic happen on all core entities cards, but also in auto_entities and others.
Now imagine having to write buttons for all of those button cards.... 

the magic line:
```
this._iconStyle = {color: stateObj.attributes.icon_color;}
```
is what made it work in custom_ui.
maybe that could be used here too?

please consider?
thanks.

**Comment by RomRider** [comment]
custom_ui being unmaintained, I don't think I'll implement that into button-card.

I think you can however implement that yourself in button card using `eval()`. Would be kind of hacky, but it should be possible.

Could you please share with me what the full state of an entity with custom-ui attributes looks like? (from the dev-tools)

**Comment by Mariusthvdb** [comment]
well, I am doing my best maintaining the forked repo.... (which I know isn't exactly the same, but we've been able to keep it alive until now ;-) )

you mean this:
```
unit_of_measurement: '%'
friendly_name: Hallway frontdoor bewegingssensor
device_class: battery
hide_attributes:
  - templates
  - editable
  - icon_color
templates:
  icon_color: >
    if (state > 75) return 'green'; if (state > 50) return 'gold'; if (state >
    25) return 'orange'; if (state > 10) return 'brown'; return 'red';
icon_color: orange

```

for the above mentioned `sensor.hallway_frontdoor_bewegingssensor`

only asking for icon_color ....

please let me know if you'd need anything else, or other entities with more complex templates (wouldn't think that to matter, since the button-card could be ignorant of the template, and only needs to see the final attribute `icon_color: orange` (in this case)?

**Comment by RomRider** [comment]
So, I think what you could do is create a template like this, and assign it as the first template to all your cards (so that anything which overrides it is still working):
```yaml
support_custom_ui:
  icon: |
    [[[
      ìf (entity && entity.attributes && entity.attributes.templates) {
        const tpl = entity.attributes.templates;
        if (tpl.icon) {
          return new Function('state', `'use strict'; ${tpl.icon}`).call(entity.state);
        }
      }
      return null;
    ]]]
  styles:
    icon:
      - color: |
        [[[
          ìf (entity && entity.attributes && entity.attributes.templates) {
            const tpl = entity.attributes.templates;
            if (tpl.icon_color) {
              return new Function('state', `'use strict'; ${tpl.icon_color}`).call(entity.state);
            }
          }
          return null;
        ]]]
```

**Comment by Mariusthvdb** [comment]
o wow, must consume this.... thanks in advance of me understanding it.

just so I understand, the section for icon: in your template above, did you write that to have button-card use the custom_ui icon template, or as a base for the icon_color template. If the former, that isn't necessary, because all my icon customizations/templates are already accepted and used by button card.

since we're experimenting here: wouldn't there be some way (maybe a new feature.... ;-) )to have this template set globally for all button cards in the config (in fact, like custom_ui itself uses customize_glob ;-)

it would be simpler than having to add it to all cards and templates

**Comment by RomRider** [comment]
> just so I understand, the section for icon: in your template above, did you write that to have button-card use the custom_ui icon template, or as a base for the icon_color template. If the former, that isn't necessary, because all my icon customizations/templates are already accepted and used by button card.

Yes, it was to display the proper icon and color. Both are independant. So you can remove one or the other.



> but unfortunately the template makes it not follow the state (it does show in steel blue, as the icon_color template dictates when 'off'. when 'on' though it neither changes icon, nor icon_color.

I think I made an error, please try this one:
```yaml
support_custom_ui:
  styles:
    icon:
      - color: |
          [[[
            if (entity && entity.attributes && entity.attributes.templates) {
              const tpl = entity.attributes.templates;
              if (tpl.icon_color) {
                return new Function('state', `'use strict'; ${tpl.icon_color}`).call(this, entity.state);
              }
            }
            return null;
          ]]]
```

**Comment by Mariusthvdb** [comment]
sorry but things getting worse, the card is not displayed at all now, and showing this error:
<img width="611" alt="Schermafbeelding 2021-01-16 om 12 11 38" src="https://user-images.githubusercontent.com/33354141/104810328-11f77980-57f4-11eb-85de-5ff3e29c9ae5.png">

**Comment by RomRider** [comment]
What's is `tjhis`? You have a typo somewhere.

**Comment by Mariusthvdb** [comment]
See my edited post above.... it's working now

**Comment by Mariusthvdb** [comment]
Just a test to see if a long stack of button cards does as I hope it would:

```
  - type: custom:auto-entities
    card:
      type: entities
      title: Test Icon color Buttons
    filter:
      include:
        - entity_id: sensor.*_actueel
          options:
            type: custom:button-card
            template: support_custom_ui
```

results in:

<img width="485" alt="Schermafbeelding 2021-01-16 om 16 31 42" src="https://user-images.githubusercontent.com/33354141/104816020-ad024a80-5818-11eb-85c3-5a4d561a088c.png">

which is a much longer stack of course, but working as expected. So this is definitely going somewhere.

**Comment by Mariusthvdb** [comment]
related question: how can we use this in a regular jinja template in the dev tools:

```
{{states.sensor.calltheboss_battery_level.attributes.templates.icon_color}}
```
gives me the template, and not the result of the template:

<img width="1486" alt="Schermafbeelding 2021-01-18 om 17 17 27" src="https://user-images.githubusercontent.com/33354141/104939718-11581200-59b1-11eb-828d-b70acee160a8.png">


while `{{state_attr('sensor.calltheboss_battery_level','icon_color')}}` returns nothing.

must confess that even after having been heavily customizing for 4 years, I've never realized this.....

**Comment by RomRider** [comment]
You can't, custom_ui templates are javascript, they won't work in jinja2.

**Comment by Mariusthvdb** [comment]
of course, I understand that....

what I thought happened with the custom_ui  icon_color, was that that sets an actual attribute icon_color to the entity. Note that we can set icon_color without template too.

And, because of that, I supposed we could template that attribute icon_color in a jinja template . Even if it was set in a custom_ui templates.

We can do that with a direct set icon_color:

```
{{state_attr('sensor.netherlands_coronavirus_confirmed','icon_color')}}
```

which is set in a custom_ui 
```
homeassistant:
  customize:
    sensor.netherlands_coronavirus_confirmed:
      icon_color: red
```

<img width="1299" alt="Schermafbeelding 2021-01-18 om 23 15 53" src="https://user-images.githubusercontent.com/33354141/104967316-5dbc4580-59e3-11eb-8ff6-793bd3f8b7f5.png">

**Comment by andrey80nik** [comment]
Have you found a solution to how to use the value of an attribute, an arbitrary object, as a value for a color?

**Comment by Mariusthvdb** [comment]
sure, check all the glob examples in https://github.com/Mariusthvdb/custom-ui/blob/master/EXAMPLES.md 

this FR should be closed though, thanks for reminding me ;-)
