### ISSUE TITLE
Fading from active color back to inactive color over configurable period of time

### ISSUE THREAD

**Issue by jhein05** [custom-cards/button-card#423]
Especially for binary sensors related to security (motion, door, etc.) it would be a helpful feature, if there was a config option to configure a time span during that the button color would fade/transition from on back to off. E.g. after detecting motion and becoming red, the button would fade over 30 minutes slowly back to grey. The color would allow the user to recognize how long ago that motion much fast than looking at the secondary_info. This would be especially helpful in a grid or similar layout, that displays buttons for multiple motion sensors. 

I am sure this is already possible with some JS tweaking, but simple config options e.g. "transition_off: 00:30:00" would make this really easy to use, without making things much more complicated.

**Comment by RomRider** [comment]
You can already do that with CSS transitions.
Here's the trick:
```yaml
styles:
  card:
    - transition: '[[[ return entity.state === "off" ? "background 5s" : null ]]]'
```

**Comment by jhein05** [comment]
I knew it :) Sorry for disturbing and thanks a lot.
