### ISSUE TITLE
Support action `fire-dom-event`

### ISSUE THREAD

**Issue by domoson** [custom-cards/button-card#429]
**Is your feature request related to a problem? Please describe.**
browser_mod switching to `fire-dom-event` away from `call-service` for popups, toasts, etc., see release notes: https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0

**Describe the solution you'd like**
Implement support for `action: fire-dom-event` in `tap_action` and `hold_action`

**Describe alternatives you've considered**
As of now `browser_mod` can still be used with `call-service` action, but might be phased out soon

**Additional context**
Thank you :-)

**Comment by RomRider** [comment]
Thanks, it's already planned, I'm just waiting on this PR to be merged: https://github.com/custom-cards/custom-card-helpers/pull/28 ;)

**Comment by domoson** [comment]
Oh wow, awesome, thanks :-)

**Comment by VDRainer** [comment]
@domoson , i copied your post to other custom-cards. Hope that's OK?

**Comment by domoson** [comment]
@VDRainer yeah sure! Thank you

**Comment by anubisg1** [comment]
any idea when this will be merged? my UI is totally broken right now

**Comment by domoson** [comment]
> any idea when this will be merged? my UI is totally broken right now

You can still use the service call.

**Comment by marcodb82** [comment]
> **Is your feature request related to a problem? Please describe.**
> browser_mod switching to `fire-dom-event` away from `call-service` for popups, toasts, etc., see release notes: https://github.com/thomasloven/hass-browser_mod/releases/tag/1.3.0
> 
> **Describe the solution you'd like**
> Implement support for `action: fire-dom-event` in `tap_action` and `hold_action`
> 
> **Describe alternatives you've considered**
> As of now `browser_mod` can still be used with `call-service` action, but might be phased out soon
> 
> **Additional context**
> Thank you :-)



> > any idea when this will be merged? my UI is totally broken right now
> 
> You can still use the service call.

I have the same problem actually i used 

`              tap_action:
                action: call-service
                service: browser_mod.popup`

in every 'custom:button-card' tap_action
but after update browser_mod to new 1.3.0 nothing happens (all is broken)
 
Can you explain please what means: " You can still use the service call."? 

tks

**Comment by RomRider** [comment]
PR has been merged, I'll release something in the evening.

**Comment by marcodb82** [comment]
> PR has been merged, I'll release something in the evening.

Exuse if i'm newbie. What means PR? .... project ? 
tks

**Comment by anubisg1** [comment]
> > PR has been merged, I'll release something in the evening.
> 
> Exuse if i'm newbie. What means PR? .... project ?
> tks

means "pull request" , it means that the changes are being accepted in the main code

**Comment by domoson** [comment]
> I have the same problem actually i used
> 
> ` tap_action: action: call-service service: browser_mod.popup`
> 
> in every 'custom:button-card' tap_action
> but after update browser_mod to new 1.3.0 nothing happens (all is broken)
> 
> Can you explain please what means: " You can still use the service call."?
> 
> tks

Did it work before? Can you post a full example with proper formatting? One thing that comes to mind is that `deviceID: this` is no longer supported. Have you tried removing it?

If nothing helps I suggest let's just wait for the new release tonight ;-) Thanks @RomRider !

**Comment by marcodb82** [comment]
Hy,  I update to last release. With Chrome and and WALLPANEL the tap_action with browser_mod for opening a POPUP now work.

Instead it doesn't work with official HA APP and also with Fullykiosk. When a tap on the button nothing happen. Someone can help.

**Comment by RomRider** [comment]
You're probably not running the latest version of either button-card or browser_mod because it's in cache. So clear the cache.

**Comment by marcodb82** [comment]
> You're probably not running the latest version of either button-card or browser_mod because it's in cache. So clear the cache.

Thank. Now Work.
