### ISSUE TITLE
custom-fields: allow buttons that contain smaller buttons, to override actions

### ISSUE THREAD

**Issue by pejotigrek** [custom-cards/button-card#430]
**Is your feature request related to a problem? Please describe.**
I'm trying to use "custom-button in custom-button" same as described [in custom-fields](https://github.com/custom-cards/button-card/blob/master/README.md#custom-fields) - for example: to display light bulbs status (small icons in corners), while the "main" button is turning the whole lamp on/off (big icon at the center) - as shown on the screenshot:
![image](https://user-images.githubusercontent.com/10796588/108086036-3d30eb00-7076-11eb-9e2b-6d3e90195ef2.png)

those tiny icons has "none" as action for tap, double tap and hold - as I don't need them.
still, when accidentaly tapped on mobile, they steal focus from the "main" button [nothing happens, so I must aim more at the center of the lamp button to take any action]

**Describe the solution you'd like**
it would be great if those buttons that have actions disabled - stopped act like disabled button, so in my case - pressing them won't steal focus, and will execute action of the "lamp" button. so the "main" button would kinda override smaller ones.

**Describe alternatives you've considered**
first I used templates [as in the example link given above] to draw icons and it's colors based on bulb's state, but when having multiple buttons with multiple smaller icons makes yaml messy, so yes, this is an alternative, but not perfect

**Comment by RomRider** [comment]
If I understand correctly, I believe the solution from this post can meet your need: https://github.com/custom-cards/button-card/issues/414#issuecomment-751848358 :)

**Comment by pejotigrek** [comment]
> If I understand correctly your request, I believe the solution from this post can meet your need: [#414 (comment)](https://github.com/custom-cards/button-card/issues/414#issuecomment-751848358) :)

oh yeah, I had some troubles on how to explain my need here, as EN is not my native language ;)

but even with my strange wording - good catch! indeed that's the solution for my "issue"! thank you :)

case closed :)
