### ISSUE TITLE
minimise border with layout card

### ISSUE THREAD

**Issue by scooper1** [custom-cards/button-card#447]
**Checklist**
- [ x] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
i wand to do borderless buttons so cards do not have a no border space between cards when using layout card grid view
i tried card-mod but don't seam to be able to override border margin 

**Version of the card**
Version: 
lastest  hacs version 
**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
That is not controlled by button-card but by the parent card of button-card ie: layout-card. Nothing I can do here.
You'll have to play with card-mod on the layout-card to achieve this.

I'm closing this.
