### ISSUE TITLE
Allow to hand over a string oder a list to a button which calls a service

### ISSUE THREAD

**Issue by fx-git-fx** [custom-cards/button-card#467]
**Is your feature request related to a problem? Please describe.**
When you define a button with

action: service

i can not hand over a string parameter or a list of parameters to that service

**Describe the solution you'd like**
Imagine a rest call defined as service (or something else you wanna call as service with a parameter). This rest call can bei called in the developer tools section of the HA backend like this:

```
service: rest_command.go_do_your_thing
data: 
  url: "/some_url_to_add?this=that&do=now"
```

I want to do that by the press on a custom button :)

**Describe alternatives you've considered**
I do not see an Alternative. The only parameter that is accepted by the action object at the moment is an Entity_id which is an Object not a string or better a list.

**Additional context**
This would help to implement buttons for cards or views that interact with a REST capable server by having one handler on the HA side which does the parametered calls.

**Comment by RomRider** [comment]
It's all written in the button-card documentation:
```yaml
tap_action:
  action: call-service
  service: rest_command.stuff
  service_data:
    url_suffix: "stuff"
```

Also rest command's url parameter supports jinja templating as written [here](https://www.home-assistant.io/integrations/rest_command/#url)

**Comment by fx-git-fx** [comment]
Hi RomRider,

sorry, i did not even guess that this may be possible. Sorry, my bad. I'm have not experience with templates until now. I do not really understand how the rendering process works and the documentation for HA does not really help.

I'am still investigating this and if it is possible i will make it some how :-) 

But if you have additional tipps for resources or a working example i would be happy to to check that out.
