### ISSUE TITLE
icon_template not followed

### ISSUE THREAD

**Issue by jaburges** [custom-cards/button-card#47]
Heya
So not sure if you have enabled this but i cant get my icon_template to work and wanted to check if you either have coded it (and its broken my end) or you havent added it?

Not sure what's easier 
icon_on
icon_off

OR
use the icon_template from the entity? 

I wondered if its possible to get a little smarter on my remote and a button to show the `mdi:play` icon or `mdi:pause` icon depending on the state of the switch.

**Comment by mrneilix** [comment]
I had to essentially make the icon template a conditional card where based on the state, it would change the icon. Not ideal, but it was the only way I could see my lock's status.

**Comment by ammmze** [comment]
as far as i know you the templates used in the home assistant config files is not possible in lovelace. The reason being the home assistant config is processed server side via the python language (which is the language the template engine (jinja2) is written in). The lovelace config is processed in your browser via javascript so we have no access to the jinja2 templating engine.

**Comment by iantrich** [comment]
Use [config-template-card](https://github.com/custom-cards/config-template-card)
