### ISSUE TITLE
Working with input_selects

### ISSUE THREAD

**Issue by DeltaNu1142** [custom-cards/button-card#475]
It occurred to me while trying to get this card to work with an input_select that it might not be performing as I expected because input_selects are not "toggleable entities." I am using a Custom Button Card to select between three possible states of an input_select and to show the color based on what state it is in. However, the colors do not update as I anticipated.

I detailed my issue here: https://community.home-assistant.io/t/strange-issue-with-custom-button-card-changing-colors-based-on-value/308455

Is it possible to allow this button card to work with the various states of an input_select, or is that a massive departure?

**Comment by RomRider** [comment]
Seems like I can close this now :)
