### ISSUE TITLE
New User: Custom element doesn't exist: button-card

### ISSUE THREAD

**Issue by shice9** [custom-cards/button-card#476]
Im quite new to Home Assistant and HACs.
I installed through HACs and added the link to resources as
URL: /hacsfiles/button-card/button-card.js
Resource type: JavaScript Module

When I go to use the custom card though on my dashboard I keep getting the error Custom element doesn't exist: button-card. I am unsure what I did wrong with the installation. Any thoughts?

**Comment by shice9** [comment]
Fixed, by changing the url pointer to: /local/community/button-card/button-card.js

**Comment by ipogodin** [comment]
@shice9 Could you please specify where have changed the pointer to : /local/community/button-card/button-card.js ??
Seems that I have the similar issue with custom button
