### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by skalavala** [custom-cards/button-card#49]
Just wanted to say **Thank you** for your work! I used the button-cards in my _lovelace_ setup, and I absolutely love it! That is the only custom card I use today. So elegant, easy to setup with great features, and of course well documented repository! We should make this functionality as part of core _lovelace_ so that everyone can enjoy the benefits.

Again, THANK YOU if I wasn't clear enough 😄

**Comment by iantrich** [comment]
@skalavala @kuuji I do agree that the core button needs to be beefed up, but this card is awesome as is and will likely prosper as a custom card much better. I hope that we can have a custom card store like the hassio add-on store at some point in the near future that will make all these awesome cards easily accessible.

I'll tack on my big THANK YOU as well 😄
