### ISSUE TITLE
Make a card take up the space of two cards

### ISSUE THREAD

**Issue by agneevX** [custom-cards/button-card#491]
Hi!

I have 5 cards in a horizontal stack, how do I get one card to take up the space of two cards, so it remains consistent across viewports?

**Comment by RomRider** [comment]
That is not related to button-card, you should use layout-card for example.

**Comment by agneevX** [comment]
This is simply a question to set a dynamic width, I'm not reporting an issue or anything like that.

I've gone through layout-card and that seems to apply to the whole of lovelace while I'd like to change only one card in a particular stack.

As an example:

I have width set to 145px, so it looks consistent with taking up the space of two cards on mobile:

<img width="340" src="https://user-images.githubusercontent.com/19761269/121848615-ea0b3400-cd07-11eb-91d1-6fb551a3a3dd.png">

However on desktop, it looks out of place:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/19761269/121848580-de1f7200-cd07-11eb-8b4e-fe3f6f658ad5.png">

**Comment by RomRider** [comment]
I know, as I said there's nothing I can do about that, that's how lovelace works. If you want control, the only option is layout-card (it can be used as a card also)

**Comment by agneevX** [comment]
Thanks! Alongside solving this issue, it has also solved some other irks about large screen layouts.
