### ISSUE TITLE
UI Editor

### ISSUE THREAD

**Issue by iantrich** [custom-cards/button-card#50]
Can now add UI Editors to custom cards. e.g. my [Roku Card](https://github.com/custom-cards/roku-card/blob/master/roku-card-editor.js)

**Comment by kuuji** [comment]
Oh that's awesome! Thanks for the example @iantrich. Your Roku cards looks pretty cool too actually, I was looking for something like that for my tv. I'll try it out.

**Comment by iantrich** [comment]
When the Roku platform released the remote in the last HA update, I couldn't resist making one 😄 
I think I mention it in the repo, but it also begs to be used with thomasloven's popup-card
![remote](https://user-images.githubusercontent.com/1287159/52029823-9bfc8980-24da-11e9-8aec-884ac1a4ca6b.gif)

**Comment by RomRider** [comment]
So much features now, I think it will be very hard to implement... 😨

**Comment by iantrich** [comment]
I gave up on using the UI for editing😜
