### ISSUE TITLE
Possibility for ''label'' option

### ISSUE THREAD

**Issue by alexreddy78** [custom-cards/button-card#508]
Hello,

Is it possible to use option ''label'' with flw string : states['binary_sensor.0x00158d0000c30470_occupancy'].last_updated | as_timestamp | timestamp_local?
 When it's inserted, card shows an error:
ButtonCardJSTemplateError: ReferenceError: as_timestamp is not defined in 'return 'Изменение ' + states['binary_sensor.0x00158d0000c30470_occupancy'].last_updated | as_timestamp | timestamp_local

However states['binary_sensor.0x00158d0000c30470_occupancy'].last_updated is working, but show UTC time

Kindly advise

Best Reragds

**Comment by RomRider** [comment]
That is not a proper Javascript template you are mixing jinja and javascript.
Maybe something like that will work:
`label: "[[[ return new Date(states['binary_sensor.0x00158d0000c30470_occupancy'].last_updated).toLocaleString() ]]]"

**Comment by alexreddy78** [comment]
Thx. Worked
