### ISSUE TITLE
Light entity color variable stopped working

### ISSUE THREAD

**Issue by matt8707** [custom-cards/button-card#509]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
Home Assistant 2021.9.0 `-light-color` and `-no-temperature` are the same colors. I think `-no-temperature` stopped working.

Dev tools:

```
--button-card-light-color: rgb(255, 136, 13);
--button-card-light-color-no-temperature: rgb(255, 136, 13);
```

**Version of the card**
Version: 3.4.2

**To Reproduce**
```yaml
```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser all
 - Version 

**Smartphone (please complete the following information):**
 - Device: 
 - OS: 
 - Browser 
 - Version 

**Additional context**

**Comment by matt8707** [comment]
Maybe related
https://github.com/home-assistant/core/pull/55219

**Comment by RomRider** [comment]
Thanks, I'll have a look
