### ISSUE TITLE
 TypeError: Cannot read property 'replaceChild' of null

### ISSUE THREAD

**Issue by Kroontje** [custom-cards/button-card#51]
Since upgraded to HA 86.x the following errors appear in the log when visiting views with the custom button-card component in Chrome and Safari:

`https:/URL:8123/frontend_latest/8ee9235853b66c6b78f9.chunk.js:3254:365 Uncaught TypeError: Cannot read property 'replaceChild' of null`

When I out-comment the custom buttond-card config there is no error.

**Comment by moskovskiy82** [comment]
Have the same issue. No matter which config i use

**Comment by IIIdefconIII** [comment]
i got a almost simulair error:

http://10.3.1.2:8123/local/button-card.js?v=0.0.5:1:39 Uncaught TypeError: Cannot convert undefined or null to object

**Comment by RomRider** [comment]
Can you try again with the latest version please?

**Comment by iantrich** [comment]
closing for no response

**Comment by Petro31** [comment]
Can we open this back up?  I believe it's related to conditional cards & the button card.  I have a whole configuration that causes many errors.  Can't really track down where it's coming from as I don't understand the debugging in the F12 for chrome.  @iantrich @RomRider

**Comment by RomRider** [comment]
Are you using vertical-stack-in-card or some other custom-cards where you nest button card inside?

**Comment by Petro31** [comment]
The view only uses vertical-stacks, horizontal-stacks, and conditional cards and custom button cards.  How do you want me to give you the configuration?  It's lengthy.  Let me see If I can recreate the issue in a smaller environment.

**Comment by RomRider** [comment]
I had this problem also with the conditional card and I switched to the [state-switch card](https://github.com/thomasloven/lovelace-state-switch) + [card-loader](https://github.com/thomasloven/lovelace-card-loader). No problem anymore for me.

**Comment by Petro31** [comment]
Ok, Let me look into that first then.

**Comment by Petro31** [comment]
@RomRider card-loader fixed it up without needing the state-switch-card.  Thanks.

**Comment by RomRider** [comment]
I still have some remaining errors but it comes from the fact that `_keyBindings` is undefined.
Same as: https://github.com/home-assistant/home-assistant-polymer/blob/dev/hassio/src/hassio-main.ts#L29-L33
@iantrich, I don't find in home-assistant-polymer any reference to that appart from the link above, any clue?

**Comment by orson1282** [comment]
I'm getting this error with conditional cards.
- When the condition is true and the card is displayed, no error.
- When the condition is false, no card should be displayed, that error shows up in the log.

**Comment by pergolafabio** [comment]
bumping on this too with my conditional cards... when the card isnt displayed
how to fix that? or only workaround is the state-switch-card?

**Comment by RomRider** [comment]
Open a new issue please and add your config and the error log. Thanks.

**Comment by pergolafabio** [comment]
Where do you want me to create issue? On frontend? Since it's not button-card related

**Comment by RomRider** [comment]
If it's happening only when you have button-cards in the view, then here, else probably in frontend yes :)

**Comment by pergolafabio** [comment]
Ok, frontend it is
