### ISSUE TITLE
Toggle opens also the more_info dialog box

### ISSUE THREAD

**Issue by RaveGun** [custom-cards/button-card#52]
With HA 0.86.4 the toggle does not toggle only, it also opens up the info dialog.

The behaviour is the same under Chrome, Opera and Android Chrome.

I tried also with the branch from Lopton where long_click toggles correctly but a simple don't.

Are there any other events generated now on click?

Thank you.

**Comment by iantrich** [comment]
This should be fixed now in 0.1.0
