### ISSUE TITLE
Fails with HACS update 11.4

### ISSUE THREAD

**Issue by donnievawter** [custom-cards/button-card#522]
**Checklist**
- [x ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
Fails to load in HA 11.4 releas
**Version of the card**
Version: 
3.4.2
**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

This stopped working with the latest HACS update.

**Comment by RomRider** [comment]
I'm not sure what you are talking about. Please provide more details.

**Comment by donnievawter** [comment]
You may close it. User error. Clearing the cache solved it. Sorry
