### ISSUE TITLE
Can I assign different actions for custom fields?

### ISSUE THREAD

**Issue by ntompson** [custom-cards/button-card#529]
I'd like to be able to assign actions differently for custom fields. Maybe it's possible, but I can't immediately see how.

I am using the `custom:button-card` to build dashboard panels to summarise the state of various systems (eg EV, heat pump, thermostats etc). Here is an example I am using for my EV:

<img width="449" alt="Screen Shot 2021-12-14 at 7 56 35 am" src="https://user-images.githubusercontent.com/32885870/145887721-4e839ac4-06e3-406b-9fc6-7711ec1c4e2c.png">

The green highlighted section is a single `custom:button-card`, with custom fields handling plug state, charge mode and range. Easiest to see the `grid` config:

```
  - type: custom:button-card
    entity: sensor.ovms_state_of_charge
    ...
    styles:
      grid:
        - grid-template-areas: >
            "zzz zzz batt soc"
            "plug mode batt soc"
            "range range batt soc"
            "yyy yyy batt soc"
        - grid-template-columns: 13% 13% 25% 49%
        - grid-template-rows: 25% 25% 25% 25%
        ...
```

At the moment, tapping on any part of the `custom:button-card` brings up `more-info` for `sensor.ovms_state_of_charge`. I'd like to be able to assign a different action to specific custom fields. For example, tapping the `range` custom field would bring up `more-info` for the associated range entity.

If there's a way to do this, I'd love to know. Otherwise, it would be a great feature to add.

As always, loving this card - it can do almost anything!

**Comment by kuduacz** [comment]
Uot of topic. 
Can u help me with few entities in one card? i mean something like yours.
cant get it.

**Comment by RomRider** [comment]
You have to embed other button card in your button card's custom_fields to be able to assign different actions on each field.

**Comment by ntompson** [comment]
OK - that makes sense @RomRider - I hadn't thought of it that way. Will make for quite a different construction - I'll give it a try.
