### ISSUE TITLE
Button's status doesn't update well and doesn't toggle on Core 2021.12.3

### ISSUE THREAD

**Issue by khaisilk1910** [custom-cards/button-card#532]
Button's status doesn't update well and doesn't toggle on Core 2021.12.3.
Please fix its!
Many thanks!

**Comment by RomRider** [comment]
Please share your config

**Comment by khaisilk1910** [comment]
> Please share your config
Sorry, that problem just for Tuya Devices. I think reason of Tuya services. Some time can not control(toggle), The state don't change. I must reload Tuya Integration.

**Comment by RomRider** [comment]
Ok, I'm going to close this then.
