### ISSUE TITLE
How to change icon color when triggering any action

### ISSUE THREAD

**Issue by Krzysztonek** [custom-cards/button-card#537]
HI,

I need to show the different action results using icon colors only.

Example: my device is AC (device class: climate)
- `tap_action` triggers `cool` mode on this device. It should change the icon color to `blue`.
- `double_tap_action` triggers `heat` mode on this device. It should change the icon color to `red`.
- hold action triggers `turn_off` the device. It should change the icon color to the default value (white, in my case).

I wrote the following code:

![obraz](https://user-images.githubusercontent.com/87784133/147358641-75d0fa6d-aeb0-4387-9b0c-c155c7792a22.png)

Unfortunately, it does NOT work as expected. I have no clue what am I doing wrongly...
The triggered actions (switch cool, switch heat, switch off) work perfectly, however, the colors of the AC icon remain permanently unchanged. 

In fact, there is no word about `color` settings under `action:` section in the button-card documentation.
Please advise how to make the color of the icon being clicked dependent on the action being triggered (see lines 13-15 and 23-25 in my code above).

Thank you in advance!

**Comment by Psychoses** [comment]
maybe something like that one :

```
                  - type: 'custom:button-card'
                    name: ButtonName
                    entity: sensor.YourSensor
                    styles:
                      icon:
                        - color: |
                            [[[
# Here you need get your hvac_mode value for set the color
# Here its a sample with just the entity.state
                              if (entity.state == 'unknown') return 'red' ;
                              elseif (entity.state == 'YourNeed') return 'YourColor' ;
                              else return 'white' ;
                            ]]]
```

**Comment by Krzysztonek** [comment]
You're GREAT! Thank you, @Psychoses 

Now my AC icon looks like below:

![obraz](https://user-images.githubusercontent.com/87784133/147645593-e0b7a98a-0b4a-4120-8b08-9ac7b504940f.png)
AC untouched (OFF)

![obraz](https://user-images.githubusercontent.com/87784133/147645729-24fbc010-36b9-4e01-86d7-cdab94e3bf93.png)
AC cool mode

![obraz](https://user-images.githubusercontent.com/87784133/147645806-fbd17150-858c-474f-923a-6a29cb38105c.png)
AC heat mode

Works perfectly, looks quite nice :) Thank you again! ☕

**Comment by RomRider** [comment]
The question seems answered, I'm going to close this :)
