### ISSUE TITLE
Long tap

### ISSUE THREAD

**Issue by mlevit** [custom-cards/button-card#55]
Hey,

For lights we need the option to open the `more_info` window to change the brightness or color of the light... but it makes sense for light buttons to have the action of `toggle` instead of `more_info`. Hence I think a long tap for the `more_info` window would make sense.

**Comment by aptonline** [comment]
This is already available in a fork of the project:
https://github.com/Lopton/button-card

However based on the breaking changes in HA 0.88 it hasn't been updated yet... as hasn't the master.

**Comment by RomRider** [comment]
Going to work on this after the next batch of PR is merged in.

**Comment by iantrich** [comment]
@thomasloven has already done most of the leg work on this https://github.com/thomasloven/lovelace-card-tools/blob/c885db9f8eafe756ff24d125cd77a5f44bb9019c/card-tools.js#L220
