### ISSUE TITLE
How do I change the button's icon color based on the value template?

### ISSUE THREAD

**Issue by fokcuk** [custom-cards/button-card#554]
I am trying to change the color of the button based on the max value of CO2 sensors. The HA syntax is 
`{{states.sensor | selectattr('attributes.device_class', 'eq', 'carbon_dioxide') | map(attribute='state') | map('float', default=0) | list | max <= 1000}}`
which returns `True`, but I cannot get it to work within the button-card:

`       - type: custom:button-card
        color_type: icon
        icon: mdi:molecule-co2
        styles:
          card:
            - height: 80px
            - width: 80px
          icon:
            - color:  >
                   [[[ 
                    if (states.sensor | selectattr('attributes.device_class', 'eq', 'carbon_dioxide') | map(attribute='state') | map('float', default=0) | list | max <= 1000)
                     return "green";
                    return "red";
                    ]]]
        tap_action:
          action: navigate
          navigation_path: /lovelace/co2
`
It looks ok to me, but I get an error:
`ButtonCardJSTemplateError: SyntaxError: Unexpected token 'default' in 'if (states.sensor | selectattr('attributes.device_class', 'eq', 'carbon_dioxide') | map(attribute=...'`

**Comment by mattague** [comment]
what was your solution to this?

**Comment by fokcuk** [comment]
> what was your solution to this?

```
      - type: custom:button-card
        color_type: icon
        icon: mdi:molecule-co2
        styles:
          card:
            - height: 80px
            - width: 80px
          icon:
            - color: |
                [[[ 
                  if (states['sensor.max_house_co2'].state <= 1000)
                    return "green";
                  return "red";

                 ]]]
        tap_action:
          action: navigate
          navigation_path: /lovelace/co2
```
