### ISSUE TITLE
how can i get the username? 

### ISSUE THREAD

**Issue by FamKeGala** [custom-cards/button-card#559]
First: im new in Hass, I love It. but I need help.
**Describe the bug**
i created 5 users AND i want the Button card appear His mame.

```
name: |
  [[[
     return user + "'sBedroom" 
  ]]]
```
But in the Button only appears [object Object]'s Bedroom

**Version of the card**
Version:  3.4.2

**Screenshots**
![Screenshot_20220218_033503](https://user-images.githubusercontent.com/99581053/154656743-59c1bea7-0ca6-46e8-bec6-1a6dc46f709e.jpg)

**Smartphone (please complete the following information):**
 - Device:  Huawei P30
 - Browser: Chrome AND edge

**Comment by SirBogner** [comment]
I don't know if you solved your problem already, but I'll give it a go:

To use 'user', you'd need to specify what you'd like to know about 'user'. In your use case the right use is 'user.name'.
