### ISSUE TITLE
Execute Javascript code on tap_action

### ISSUE THREAD

**Issue by vlaraort** [custom-cards/button-card#577]
**Is your feature request related to a problem? Please describe.**
I would like to dispatch a JS Event from a button-card tap_action, more concrete, in my case I want to dispatch 'hass-toggle-menu', so I can create a custom button-card that toggles the menu sidebar, and remove the default bar in my theme

**Describe the solution you'd like**
I would like to have another kind of action, maybe 'custom', in which I can set up a JS to be executed, something like this:

```
  tap_action:
    action: 'custom'
    custom_action: |
      [[[
        this.dispatchEvent(new Event('hass-toggle-menu', { bubbles: true, composed: true}))
      ]]]
```

**Describe alternatives you've considered**
I have tried something like:

```
  tap_action:
    action: |
      [[[
        this.dispatchEvent(new Event('hass-toggle-menu', { bubbles: true, composed: true}))
        return 'none'
      ]]]
```

But the problem is that is executed in the initialization besides the tap_action, so the event is dispatched and my menu is opened when the button is loaded

**Additional context**
This feature would be really nice not only for my usecase, but for anybody that wants to do any frontend related process

**Comment by RomRider** [comment]
Please see here: https://github.com/custom-cards/button-card/issues/314#issuecomment-616258963
