### ISSUE TITLE
Is it possible to access the card's icon through JavaScript templates?

### ISSUE THREAD

**Issue by adabelleleiram** [custom-cards/button-card#587]
**Is your feature request related to a problem? Please describe.**
I've created a template card where each implementation sets its own icon (instead of using the entity's default icon). I would like to reuse this icon in one of the custom_fields cards but don't seem to be able to access the icon's value through JavaScript. Maybe there's another way to do it? Preferably not by adding it to the variables object.

**Describe the solution you'd like**
To be able to access the card's icon value in JavaScript e.g.

> custom_fields:
>> sub_card:
>>> card:
>>>> icon: "[[[ return icon; ]]]"

**Comment by Garulf** [comment]
This *should* work.
```
icon: '[[[ return this._config.icon; ]]]'
```

**Comment by u8915055** [comment]
I just want to say that this really solved a big problem i was having.. I was trying to embed the entity's icon into a custom field (button within a button sort of thing) and when i embedded a button card within a button card, it would pick up the default icon for the entity 'light' and not my custom one.  Your statement solved my problem .. Thank you!!!

<img width="571" alt="image" src="https://user-images.githubusercontent.com/35235070/202877651-316b80d8-59cb-4891-8e99-425385826bc9.png">

**Comment by adabelleleiram** [comment]
> This _should_ work.
> 
> ```
> icon: '[[[ return this._config.icon; ]]]'
> ```

Sorry for taking so long to reply but this solved it! Thanks a bunch!
