### ISSUE TITLE
Entity Character Length

### ISSUE THREAD

**Issue by beerfuzz** [custom-cards/button-card#589]
**Describe the bug**
When creating custom buttons if the characters in the entity name exceed 28 then the color function ceases to work. Examples below. 

**Version of the card**
Version: 

**To Reproduce**
This is the configuration I used:
```
type: custom:button-card
template: motion_button
name: Kitchen
entity: script.motion_trigger_kitchen

```

**Screenshots**
If you look at the screen shot if I remove the 29th character.. the button color works. 

**Expected behavior**
I don't know what the limit on character length for entities is supposed to be but some of mine have longer than 28 characters.

**Desktop (please complete the following information):**
I have used this in many browsers and on multiple devices that have all had the cache cleared and the system rebooted. 

**Additional context**
![Code](https://user-images.githubusercontent.com/104107485/167625722-4ce468ea-40e2-4e98-8741-97b9506139a3.png)
![Buttons](https://user-images.githubusercontent.com/104107485/167625689-62748ff5-c7f7-4931-a150-bf7712af8546.png)
Hallway with Y
![Buttons Long Hallway](https://user-images.githubusercontent.com/104107485/167625690-a03634a6-bfca-448f-8e14-e9a99f92cdab.png)
Hallwa without Y
![Buttons Short Hallway](https://user-images.githubusercontent.com/104107485/167625693-00980b82-361f-4695-bcfc-06f106d63218.png)

**Comment by RomRider** [comment]
Please share your full template.
