### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by IIIdefconIII** [custom-cards/button-card#61]
since 0.88
virt env
no traceback

http://10.3.1.2:8123/local/button-card.js?v=0.0.5:1:39 Uncaught TypeError: Cannot convert undefined or null to object

**Comment by PierpaoloPernici** [comment]
check #57 and #62

**Comment by ammmze** [comment]
Buttons should load (once you update your `button-card.js`) now that #63 has been merged

**Comment by bouwew** [comment]
![image](https://user-images.githubusercontent.com/11290930/53284628-53da2b00-3757-11e9-8d4c-e69c2b09acec.png)

Do this and select

**Comment by artomka** [comment]
After upgrading to the version 0.0.6 I still have the same error “Cannot convert undefined or null to object”.

**Comment by bouwew** [comment]
I had the same issue, it is caused by your browser, see the solution for Chrome in my previous post.

**Comment by IIIdefconIII** [comment]
saw alot of converstation this week, is the one on the main github now the latest?

**Comment by CrazYoshi** [comment]
> I had the same issue, it is caused by your browser, see the solution for Chrome in my previous post.

I empty the cache and reload but I have the same error: "Uncaught TypeError: Cannot convert undefined or null to object"

**Comment by iantrich** [comment]
Is this still an issue?

**Comment by bouwew** [comment]
No, the provided solution works.
