### ISSUE TITLE
lock only for x seconds

### ISSUE THREAD

**Issue by Goeste** [custom-cards/button-card#617]
Hi,

I was wondering if there is an option to have card locked only for a certain amount of time?

I.e. I tap a card to start a digital picture frame. The rpi needs some time to boot up and this process should not be interrupted by a mistake (since the card also switches the frame of as well). Therefore a lock would be needed that is persistant for X seconds. After that time the frame can be safely shut down and the card should be unlocked automatically.

Thanks for any help on this.

Best, Felix

**Comment by Goeste** [comment]
case closed.

**Comment by Goeste** [comment]
solved

**Comment by EddyK69** [comment]
> solved

i have the same question, so how did you solve this?
