### ISSUE TITLE
button_card_templates only accepts one location and cannot merge directories

### ISSUE THREAD

**Issue by Marck** [custom-cards/button-card#628]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
Not really a bug but more of a question I guess.

I'm having a bit of a issues with my home-assistant setup using button-card with multiple directories in different locations.
I have a folder where my minimalist code is along with the button card code (path: `/config/workspace/custom_components/ui_lovelace_minimalist`)

I also have a few dashboard that need the code from the minimalist directory AND the custom cards directory that is in a different location. 

_Why do I have it in a different location?_
Simple: because if HACS updates my minimalist folder it removes everything and all my custom cards would be gone. (path for the custom_cards: `/config/workspace/dashboards`).

**Version of the card**
Version: 3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
button_card_templates: !include_dir_merge_named "../../ui_lovelace_minimalist/lovelace/ulm_templates/"
```

**Screenshots**

**Expected behavior**
A way to let the `button_card_templates:` variable merge multiple directories that are in different locations. I have now the following configuration that cannot merge the two locations (if I define it later, it picks the later defined location):
`button_card_templates: !include_dir_merge_named "../../ui_lovelace_minimalist/lovelace/ulm_templates/"`

I would like something like this:
```yaml
button_card_templates: 
     - !include_dir_merge_named "/config/workspace/custom_components/ui_lovelace_minimalist"
     - !include_dir_merge_named "config/workspace/dashboards/custom_cards/"
```
OR a way to better take care of this with two directories. I tried every HASS include option (as described here: https://www.home-assistant.io/docs/configuration/splitting_configuration/#advanced-usage) but nothing works with two different locations sadly.

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]: chrome
 - Version [e.g. 22]: 106.0.5249.119

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: -
 - OS: [e.g. iOS8.1]: -
 - Browser [e.g. stock browser, safari]: -
 - Version [e.g. 22]: -

**Additional context**
The alternative I have is to place all my custom_cards in the location where also my minimalist code is (`/config/workspace/custom_components/ui_lovelace_minimalist/custom_cards`) but that gets wiped after each update of minimalist. 

If I have mislabed this as a bug, please point me to the correct form/label.

**Comment by Marck** [comment]
Closing this for I have a workaround and it will probably never get answered.

**Comment by imrs776** [comment]
@Marck can you describe how did you achieve it? because I need exactly the same thing

**Comment by Marck** [comment]
> @Marck can you describe how did you achieve it? because I need exactly the same thing

I have put my custom cards in a GitHub repo and included that as a git submodule at this location: /config/workspace/custom_components/ui_lovelace_minimalist/custom_cards

If I have an update, I just revert the removal of the submodule
