### ISSUE TITLE
Center the whole view 

### ISSUE THREAD

**Issue by Wolk9** [custom-cards/button-card#648]
I'm dying to be able to center my buttons on a dashboard or at least want to be abel to center my button's within an horizontal stack. Why is that so hard? 

A simple feature to center a stack of buttons would be nice

Although I could simulate centered buttons with empty buttons on both sides it is not precise and workable.

**Comment by Opontios** [comment]
If you want somebody to help you, wouldn't it be reasonable to paste the code of your card and the items you want to center?

**Comment by RomRider** [comment]
That's how HA works, there's nothing I can do about that.
You can use layout-card maybe.
