### ISSUE TITLE
blank-card has a border

### ISSUE THREAD

**Issue by harristom** [custom-cards/button-card#652]
**Checklist**
- [x ] I updated the card to the latest version available
- [x ] I cleared the cache of my browser

**Describe the bug**
Setting color type to blank-card creates a visible card (specifically, I think it is the border that is visible)

**Version of the card**
Version: v3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:button-card
color_type: blank-card
```

**Screenshots**
![image](https://user-images.githubusercontent.com/51212431/213750652-f5fa0e41-741e-4cef-9632-d8c883a8449f.png)

**Expected behavior**
No card should be visible

**Desktop (please complete the following information):**
 - Browser: Edge
 - Version 109.0.1518.55 (Official build) (64-bit)

**Additional context**
None

**Comment by rbisschops** [comment]
Also see this behavior in Windows10 - Chrome Version 109.0.5414.121 (Official build) (64-bits); iOS - Chrome version 110.0.5481.83

**Comment by alanthewild** [comment]
Seeing the same behaviour in:
- MacOS Ventura 13.1, Chrome version 109.0.5414.119 (Official Build) (arm64)
- MacOS Ventura 13.1, Safari version 16.2 (18614.3.7.1.5)
- iPhone 13 - iOS 16.2, Chrome version 110.0.5481.83

Issue is **NOT present in Home Assistant 2022.7.7**, Frontend 20220707.1 - latest
Issue is present in Home Assistant **2022.12.8**, Frontend 20221213.1 - latest
Issue is present in Home Assistant **2023.2.5,** Frontend 20230202.0 - latest
All using same button-card v3.4.2

**Comment by Mariusthvdb** [comment]
all cards have that since a recent change.
set `ha-card-border-width: 0px` in your theme and it is gone.

or add that to a specific button-card, if you don't want to change the overall look in the Dashboard
