### ISSUE TITLE
Custom:button-card to use for the “my position” of my blinds not working

### ISSUE THREAD

**Issue by slingshot74** [custom-cards/button-card#660]
Hi,

I have blinds and with the my button the blinds go to the “my position”/

When I use a normal button everything works fine with this code:
`
show_name: true
show_icon: true
type: button
tap_action:
  action: toggle
entity: button.werkkamer_my_position`

I want to use the custom:button-card
When i don’t specify an action the tap_action should be default - toggle
But when i push the button I got the “more information” screen.

`type: custom:button-card
entity: button.werkkamer_my_position
color_type: icon
color: steelblue
show_entity_picture: true
icon: mdi:star
label: My tuin
show_label: true
show_name: false
styles:
  card:
    - height: 100px`

When I add tap_action: toggle
nothing happens when I push the button.

`type: custom:button-card
entity: button.werkkamer_my_position
color_type: icon
color: steelblue
show_entity_picture: true
icon: mdi:star
label: My tuin
show_label: true
show_name: false
tap_action: toggle
styles:
  card:
    - height: 100px`

**Comment by Opontios** [comment]
```
tap_action:
  action: toggle
```
This is the syntax.

**Comment by slingshot74** [comment]
@Opontios 
Unfortunately that didn't work.

I get the error:
Failed to call service button/turn_off. Service not found.

`type: custom:button-card
entity: button.ouders_achtertuin_my_position
color_type: icon
color: steelblue
show_entity_picture: true
icon: mdi:star
label: My tuin
show_label: true
show_name: false
tap_action:
  action: toggle
styles:
  card:
    - height: 100px`

**Comment by slingshot74** [comment]
@Opontios Unfortunately that didn't work although I get an error now.

Code:
type: custom:button-card
entity: button.ouders_achtertuin_my_position
color_type: icon
color: steelblue
show_entity_picture: true
icon: mdi:star
label: My tuin
show_label: true
show_name: false
tap_action:
  action: toggle
styles:
  card:
    - height: 100px
    
**Error:
Failed to call service button/turn_off. Service not found.**
