### ISSUE TITLE
code turns into array after reboot 

### ISSUE THREAD

**Issue by Pocky0013** [custom-cards/button-card#665]
**Checklist**
- [X ] I updated the card to the latest version available
- [ X] I cleared the cache of my browser

**Describe the bug**
code turns into array after reboot and no longer works

**Version of the card**
Version: 3.4.2

I have the following code, with the following snippet
![Capture d’écran 2023-03-17 à 17 26 41](https://user-images.githubusercontent.com/111347509/225963817-33d8d37b-45ef-4731-b974-d3871fb08deb.png)

    styles:
      card:
        - background-color: '#17AB48'
        - height: 25px

after a reboot of HA or in a random way that I haven't figured out yet. The code display the error in faulty code of the transformation into array of tags.

    styles:
      card:
        '0':
          background-color: '#17AB48'
        '1':
          height: 25px

![Capture d’écran 2023-03-17 à 17 26 00](https://user-images.githubusercontent.com/111347509/225963866-b4e613ec-10e1-4067-bc32-5e2ffa0461dc.png)

If I change delete display to array to put back one "- " everything works again

**Comment by RomRider** [comment]
This seems to have nothing to do with button card but with a bug in the editor of HA. I'm closing this here. Please open an issue in the frontend repo of HA if you still have the issue.
