### ISSUE TITLE
Button-card broken in HA 2023.4 (beta) Dont update if you use button-card

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#669]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**

2023.4 beta launched today, and the many changes in the frontend cause button-card to no longer be functional.

according to Frontend dev this might be an issue:

- custom-card-helpers is broken, it walks through DOM elements and something changed in those elements

**Version of the card**e 
Version: 

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**

<img width="1072" alt="Scherm­afbeelding 2023-03-30 om 09 20 41" src="https://user-images.githubusercontent.com/33354141/228772810-34f556c9-d716-4a93-9c4c-bd32f281bcf1.png">

**Expected behavior**

Seems obvious... ourDashboard to be functional with the best card around

**Desktop (please complete the following information):**
Any

**Smartphone (please complete the following information):**
Any

**Additional context**

This seems to be a generic issue with the card, I didnt have a chance to find a specific detail yet, had to roll back to 2023.3.6 in order to have a functional frontend....

in the #beta on Discord it was mentioned that the same also applies to Decluttering-card and Apex-charts-card.

Hope you're still around RR, and can find the time to fix these so very fundamental cards.

**Comment by tomlut** [comment]
Cause: https://github.com/RomRider/apexcharts-card/issues/527#issuecomment-1489919658

**Comment by guevara777** [comment]
I forked this repository, made the changes and tried to add it as a "custom repository to hacs. 

That doesn't work
![image](https://user-images.githubusercontent.com/29648553/229273572-39cdb2a7-9f94-441f-8052-9b04391b1287.png)

Any ideas how to get the card back to work again? 

I need help, please.

**Comment by kulmegil** [comment]
I'm not smart enough to actually provide more insightful help as I lack the experience, but here is the link for requirements:
https://hacs.xyz/docs/publish/plugin

I'm pretty sure hacs needs to locate a valid build .js file 
(either attached to latest release or in repo root or /dist folder)

Not sure how crash with button-card already being a part of default repos list.
(is unique repo name required?)

**Comment by Mariusthvdb** [comment]
I have it on good authority, we have to wait until Monday, and some mysterious dev will have a look and release a fix....so have some patience, (and until that time, edit the resource manually)

**Comment by guevara777** [comment]
> I have it on good authority, we have to wait until Monday, and some mysterious dev will have a look and release a fix....so have some patience, (and until that time, edit the resource manually)

This is wonderful news. I´ve used the button-card very often in my dashboard and it looks like shi... right now. Thank you very much! 💯

**Comment by guevara777** [comment]
> I have it on good authority, we have to wait until Monday, and some mysterious dev will have a look and release a fix....so have some patience, (and until that time, edit the resource manually)

I´ve edited the resource here:
![image](https://user-images.githubusercontent.com/29648553/229278385-0acef604-c701-4782-9e2a-bd7257cc81ff.png)

I´ve replaced
![image](https://user-images.githubusercontent.com/29648553/229278426-4a273506-9b50-4ae3-bd8b-c8223ac859e8.png)

with
![image](https://user-images.githubusercontent.com/29648553/229278458-8432b3ec-b24e-4dd9-86da-de7cc2194253.png)

and restarted ha. Sadly it still looks the same. 

What did i do wrong?

**Comment by Mariusthvdb** [comment]
you probably still have it in the HACS folder? and use the HACS resource techniques, which can not be fooled easily. ;-)

make a new resource,  add it in another folder in www, and point the resources file to that new resource. You can do that in Yaml mode, or via the UI

**Comment by guevara777** [comment]
> you probably still have it in the HACS folder? and use the HACS resource techniques, which can not be fooled easily. ;-)
> 
> make a new resource, add it in another folder in www, and point the resources file to that new resource. You can do that in Yaml mode, or via the UI

you're right. It is still in the Hacs folder. I´ll try that. Thank you ❤️

**Comment by firstof9** [comment]
delete the `.gz` files first THEN edit the `.js` file.

**Comment by RomRider** [comment]
I'll fix that Monday, folks.

**Comment by Mariusthvdb** [comment]
RomRider, you're the best! Do notice https://discord.com/channels/330944238910963714/427516175237382144/1091751687221424159 though....

OK, I know you will all hate me for doing this, but believe me it is better to do it now then later 😬 
We will rename `mwc-drawer` to `ha-drawer` during the beta (hopefully next beta)
This means all custom cards that where updated to `mwc-drawer` should now be updated again to `ha-drawer`

**Comment by RomRider** [comment]
Note: I've updated it directly to use `ha-drawer`

**Comment by Mariusthvdb** [comment]
Great. Much appreciated! Beyond joy here.

**Comment by modem158** [comment]
Anyone else still having this issue?  I've updated to 3.5.0 and I'm using the cards with Lovelace Minimalist.  Cleared cache and all that jazz to no avail.

**Comment by modem158** [comment]
@kulmegil looks like it's me. I connect to HA at work through Nabu Casa and for some reason that browser refused to show my cards all day (even with a cache clear and restart).  It's working fine on my phone and at home.  Strange behavior that I couldn't clear my cache at work and have it reload properly.  I'll play some more tomorrow.  Thanks for your reply.
