### ISSUE TITLE
after Beta release 2023.4.0b I get an error message: null is not an object (evaluating 't.config

### ISSUE THREAD

**Issue by Trouble-51** [custom-cards/button-card#671]
**Checklist**
- [x ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**

the full dubble error messages are in the log is:

Logger: frontend.js.latest.202303300
Source: components/system_log/__init__.py:254 
First occurred: 11:13:04 (4 occurrences) 
Last logged: 11:21:03

http://192.168.68.54:8123/hacsfiles/kiosk-mode/kiosk-mode.js?hacstag=497319128173:1:5301 TypeError: null is not an object (evaluating 'i.querySelector')
http://192.168.68.54:8123/hacsfiles/lovelace-layout-card/layout-card.js?hacstag=156434866244:13:3316 TypeError: undefined is not an object (evaluating 'this._observer.disconnect')

**Version of the card**
Version: V3.4.2

**To Reproduce**
This is the configuration I used:
```yaml
type: custom:layout-card
layout_type: masonry
max_cols: 3
with: 300
theme: Home
cards:
  - type: custom:button-card
    template: header_red
    name: Hourly Weather
  - type: custom:hourly-weather
    entity: weather.tomorrow_io_casa_girassol_hourly
    icons: false
    label_spacing: '2'```

**Screenshots**
If applicable, add screenshots to help explain your problem.

<img width="508" alt="Screenshot 2023-03-31 at 10 48 30" src="https://user-images.githubusercontent.com/26715092/229099332-e98bf59e-42e9-4fd4-9c2a-6caf08377658.png">


**Expected behavior**
A clear and concise description of what you expected to happen.

this started when I upgrade to the last beta version 2023.4.0.b2

**Desktop (please complete the following information):**

safari: Version 16.3 (18614.4.6.1.6)
Chrome: Version 113.0.5668.0 

 OS:macOs ventura 13.2.1

**Smartphone (please complete the following information):**
 - Device:  iPhone12



**Additional context**
Add any other context about the problem here.

**Comment by Mariusthvdb** [comment]
see https://github.com/custom-cards/button-card/issues/669
