### ISSUE TITLE
Install button-card as a resource once?

### ISSUE THREAD

**Issue by redlefloh** [custom-cards/button-card#683]
Could button-card be installed like other modules via a resource configuration entry once e.g. in http://<ha-ip>:8123/config/lovelace/resources instead of adding the resource to every dashboard.yaml file that uses it?

An example for a modeule that does it that way is: https://github.com/benct/lovelace-multiple-entity-row 

Thanks for considering it!

**Comment by Mariusthvdb** [comment]
nothing to consider, it has been like this since its conception..

**Comment by RomRider** [comment]
Not sure what this is about?
