### ISSUE TITLE
Polymer is deprecating - possible button-card related errors in log?

### ISSUE THREAD

**Issue by pejotigrek** [custom-cards/button-card#684]
**Checklist**
- [X] I updated the card to the latest version available
- [X] I cleared the cache of my browser

**Describe the bug**
I'm heavily editing my button-card based dashboard right now, and while refreshing the view to see my changes, there are random errors in homeassistant's log:

`2023-04-13 16:37:08.224 WARNING (MainThread) [frontend.js.latest.202304110] WARNING: Polymer will be removed from window in Home Assistant 2023.5. More info: https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer`

I am not totally sure if this is button-card related [error in the log is slightly unprecise...] but I've searched button-card repository for _Polymer_ keyword, and found few matches in the code, so the question is - should we all be worried and not update HA to 2023.5 when it shows up?

**Version of the card**
Version: 3.5.0

**Expected behavior**
No errors in the log

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version 112.0.5615.87

**Comment by Mariusthvdb** [comment]
This is totally Not custom:button-card....

Please close..

**Comment by Mariusthvdb** [comment]
Sure, those are copyright mentions.

Not actual code usage.

Before raising issues please always disable all custom cards except the one you are actually debugging.

If the warning still occurs you might have a valid contender ;-)
