### ISSUE TITLE
Custom updater

### ISSUE THREAD

**Issue by Bastiencc** [custom-cards/button-card#69]
Hey
this url is 404, https://raw.githubusercontent.com/kuuji/button-card/master/tracker.json
is there an other tracker to add on custom updater?

**Comment by SeanPM5** [comment]
```
resources:
  - url: /customcards/github/custom-cards/button-card.js?track=true
    type: module
```

**Comment by Bastiencc** [comment]
thanks ! i do not need an card_urls on the custom_updater component anymore ?

**Comment by ludeeus** [comment]
correct @Bastiencc
