### ISSUE TITLE
State shown in wrong language

### ISSUE THREAD

**Issue by matthiasgross** [custom-cards/button-card#690]
Browser and system language is german.

Show_state is set to true; state is shown as "home" instead of "zu hause".
State of the entinity in the menu of the entinities as it should be

Same behaviour for other entities: "on" instead of "an.
And so on.

Changing the language to spanish does not change anything.

version v3.5.0

YAML - This is the configuration I used:
type: custom:button-card
entity: person.matthias
name: Matthias
show_state: true

windows 11, firefox version 112

![2023-05-01_16h15_33](https://user-images.githubusercontent.com/75206509/235465485-fa28f06c-7c8b-4901-9db7-bc6b6735f602.jpg)

**Comment by ratunee-me** [comment]
I feel the same way. I hope it gets resolved quickly.

**Comment by ildar170975** [comment]
Possibly duplicates https://github.com/custom-cards/button-card/issues/685

**Comment by matthiasgross** [comment]
https://github.com/custom-cards/button-card/issues/685
