### ISSUE TITLE
show_last_updated

### ISSUE THREAD

**Issue by Kedryn** [custom-cards/button-card#701]
**Is your feature request related to a problem? Please describe.**
Missing a way to show the time from the last update to te displayed entity

**Describe the solution you'd like**
a "show_last_updated" like the "show_last_changed" to display the time since last sensor update (expecially for button related to gps positions)

**Comment by andyblac** [comment]
and a `show_last_actioned` for when the last time a scene was run.

**Comment by Mariusthvdb** [comment]
did you try 
```
      state_display: >
        [[[ return entity.last_updated; ]]]
      show_state: true
```

@andyblac what is `show_last_actioned` ...... iow, how would you expect button_card to show a non existing state attribute?

**Comment by andyblac** [comment]
well, when I use `show_last_changed: true` for a scene button for example, it does not show the last time the scene was accually run, unlike the lovelace entity card. It just seems show the last time anything happened, i.e. if you restart HA the time just gets that time, or if you chnage the scene thats the time it shows. but it does also show the last action time IF nothing has touched the scene since it was last run.

what I am after is a NEW varible that is acutally linked to the state date time, but in human readable format.
<img width="606" alt="Screenshot 2023-07-12 at 11 02 21" src="https://github.com/custom-cards/button-card/assets/77936/03410a9f-4b7d-488a-82e3-c817f90ac3b6">

or is there another way I don't know about ????

**Comment by RomRider** [comment]
Will be possible with the next release with `state_display: [[[ return formatDateTime(entity.state); ]]]` for example in your case.

**Comment by Mariusthvdb** [comment]
this is in b7? I cant take it happen I am afraid.

**Comment by RomRider** [comment]
Not yet released. Fixing some bugs with other stuff.

**Comment by Mariusthvdb** [comment]
<img width="382" alt="Scherm­afbeelding 2023-07-24 om 23 15 02" src="https://github.com/custom-cards/button-card/assets/33354141/639b0399-2a33-4bf7-ba0e-853d66dc2f19">

beautiful!

```
type: custom:button-card
entity: script.aan_de_slag
show_state: true
state_display: |
  [[[ return formatDateTime(entity.attributes.last_triggered); ]]]
```

**Comment by andyblac** [comment]
@RomRider would it be posible to add the ability the convert to `relative time`, i.e. `36 Seconds ago`, `2 Minuets, 36 Seconds ago`, `1 Hour, 36 Minuets ago` ?

**Comment by RomRider** [comment]
The difference with relative time is that it needs to update over time automatically like when using show_last_updated so that's something different.
I'll see what I can do as I wasn't aware about the last_changed property until reading this thread 😅

**Comment by Mariusthvdb** [comment]
if I am allowed to piggyback on this:
would it be possible to only show `FormatTime` ? (making that up as I type, so dont take it to be an existing format)

for many of those last_changed/triggered/updated entities the dat is not important, the time would be though. Having a dedicated setting for it would be very much appreciated

**Comment by andyblac** [comment]
@RomRider Thanks, it's just the standard lovelace entity card uses relative time when using a scene entity

**Comment by RomRider** [comment]
Actually, I'm thinking you could do something like:
```yaml
state_display: |
  [[[
    return html`
          <ha-relative-time
            id="last_changed"
            class="ellipsis"
            .hass="${hass}"
            .datetime="${entity.state}"
          ></ha-relative-time>
        `
  ]]]
```

This will automatically update over time.

**Comment by RomRider** [comment]
In the next version about to be published, I've introduced a `relativeTime` function.

So you'll be able to do something like:
```yaml
state_display: '[[[ return relativeTime(entity.state); ]]]'
```

And it will update automatically over time.

**Comment by RomRider** [comment]
Breaking change in the latest beta on this, please read the release notes ;)
