### ISSUE TITLE
Tap event is not handled by button card but its embedded card

### ISSUE THREAD

**Issue by panhans** [custom-cards/button-card#705]
Hi there,

I have a sensor card embedded into a custom:button-card in order to have custom hold and tap actions. But it seems the embedded card is on top.
E.g. the tap event is not handled by the button card but by the embedded sensor card. Is there a way to prevent this behaviour so the events get handled by the parent button card?

Thanks in advance!

**Comment by Opontios** [comment]
Why not to use the embedded tap and hold acttion of the custom button card?

**Comment by panhans** [comment]
> Why not to use the embedded tap and hold acttion of the custom button card?

The embedded card doesn't support custom actions. https://www.home-assistant.io/dashboards/sensor/

**Comment by RomRider** [comment]
Set `pointer-events: none` on the style of the custom_field

**Comment by panhans** [comment]
> Set `pointer-events: none` on the `styles` of the custom_field of the embedded card

Thanks! That did the trick!

**Comment by panhans** [comment]
closed & solved
