### ISSUE TITLE
unsafeHTML() called with a non-string value

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/button-card#725]
**Checklist**
- [ ] I updated the card to the latest version available
- [ ] I cleared the cache of my browser

**Describe the bug**

after the latest update to 400 dev5 (might have been earlier in the dev version, but didnt notice) a button using:
```
custom_fields:
  notification: >
    [[[ return Math.round(states['sensor.pond_buiten_sensor_temperature'].state); ]]]
```

throws 

<img width="1388" alt="Scherm­afbeelding 2023-07-24 om 09 31 14" src="https://github.com/custom-cards/button-card/assets/33354141/a02f60b6-b260-4833-8c43-99b5c71d44e0">

and doesnt show.

Commenting that makes the card appear

**Version of the card**
Version: 
4.0.0.dev-5

**To Reproduce**
This is the configuration I used:

on another card I just found the same things happens when using
```yaml
 custom_fields:
   notification: >
     [[[ return entity.attributes.current_position; ]]]

```

**Screenshots**

no card:

<img width="158" alt="Scherm­afbeelding 2023-07-24 om 09 32 45" src="https://github.com/custom-cards/button-card/assets/33354141/54a5dea3-205b-43e2-9871-f027efd2dceb">

without the notification field:

<img width="141" alt="Scherm­afbeelding 2023-07-24 om 09 33 01" src="https://github.com/custom-cards/button-card/assets/33354141/bf5e8647-c30c-4553-bbb8-0ba8494108f5">

showing a default state value.

**Expected behavior**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Any 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RomRider** [comment]
Can you try with `[[[ return Math.round(states['sensor.pond_buiten_sensor_temperature'].state).toString(); ]]]` as it says it needs to be a string :)

**Comment by RomRider** [comment]
Ok, I think I found the bug. Odd it didn't trigger before as this code is there forever...

**Comment by Mariusthvdb** [comment]
yes, its odd indeed, as my butto has been there for ever too ;-)

btw, can this be caused by the same thing?:

<img width="817" alt="Scherm­afbeelding 2023-07-24 om 13 07 55" src="https://github.com/custom-cards/button-card/assets/33354141/8c669f91-005a-4b73-baab-1b8654d2a140">

got nowhere to look without anything further

**Comment by Mariusthvdb** [comment]
<img width="760" alt="Scherm­afbeelding 2023-07-24 om 13 10 32" src="https://github.com/custom-cards/button-card/assets/33354141/ad3e5cb9-7af8-411c-98e4-fb3260b51b1f">

so I have a template error, that narrows it down....
just odd there is no originator here in the error

**Comment by Mariusthvdb** [comment]
I found the template_error in connection.js....

it's not you ;-)
it was me in a card-mod-theme template. sorry about that.

**Comment by RomRider** [comment]
I'll look further into that... very strange :)

**Comment by RomRider** [comment]
4.0.0-dev7 will fix that, please let me know if you see some other strange behaviors because of the fix.

**Comment by Mariusthvdb** [comment]
believe we can safely close this? I havent seen it any more since that fix..

**Comment by RomRider** [comment]
It's going to close automatically on stable release, no worries
