### ISSUE TITLE
iOS10.3

### ISSUE THREAD

**Issue by PierreScerri** [custom-cards/button-card#73]
Hi

Button-card does not work with iOS 10.3. I get 'Custom element doesn't exist'.

Works fine on iOS12 and MacOS Mojave

**Comment by ludeeus** [comment]
Most (if not all) custom cards will have this issue.
You should update your hardware, or _maybe_ try chrome on it.

**Comment by PierreScerri** [comment]
Fine suggestion.  Throw away perfectly useable iPad!

And no, quite a few of them work.

Thank you.

**Comment by r0l01** [comment]
I agree with @PierreScerri.  Got a perfectly good iPad2 and the card doesn't work with any browser (Safari, Chrome and Mozilla).

I need to find another solution to replace the button-card.
