### ISSUE TITLE
Android&chrome: element don't exist

### ISSUE THREAD

**Issue by LeidenSpain** [custom-cards/button-card#74]
Hi,

I'm using your custom card with all updated (HA 0.89.1 and the last version of button-card).

I have the problem that the card don't work on android and chrome:
![image](https://user-images.githubusercontent.com/45803748/54240182-9e142800-451d-11e9-9434-8bf867c86e37.png)

The 2 first are the oficial button component, and the other are your card.

I have tried everything but nothing works

Regards

**Comment by ludeeus** [comment]
https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#common-problems

**Comment by LeidenSpain** [comment]
Hi,

I just looked at it again, and now it looks right.

Regards
