### ISSUE TITLE
How to remove the thousands separator in a numeric display?

### ISSUE THREAD

**Issue by db-one** [custom-cards/button-card#750]
![image](https://github.com/custom-cards/button-card/assets/20243226/7fb36c04-b256-45ee-96ad-08854f924a79)

How to remove the thousands separator in a numeric display?
Thank you so much

square: false
columns: 3
type: grid
cards:
  - type: custom:button-card
    entity: sensor.pve_cpu_temp
    name: CPU温度
    show_state: true
    show_units: true
    numeric_precision: 0
    icon: mdi:fan
    layout: icon_name
    size: 25px
    styles:
      name:
        - line-height: 35px
        - padding-right: 30px
      state:
        - font-size: 2em
        - font-weight: bold
        - line-height: 40px
        - color: '#d3d3d3'
  - type: custom:button-card
    entity: sensor.pve_cpu_fan
    name: CPU风扇
    show_state: true
    show_units: false
    icon: mdi:fan
    layout: icon_name
    size: 25px
    styles:
      name:
        - line-height: 35px
        - padding-right: 30px
      state:
        - font-size: 2em
        - font-weight: bold
        - line-height: 40px
        - color: '#d3d3d3'
  - type: custom:button-card
    entity: sensor.pve_sys_fan
    name: 系统风扇
    show_state: true
    show_units: false
    icon: mdi:fan
    layout: icon_name
    size: 25px
    styles:
      name:
        - line-height: 35px
        - padding-right: 30px
      state:
        - font-size: 2em
        - font-weight: bold
        - line-height: 40px
        - color: '#d3d3d3'

**Comment by RomRider** [comment]
By default, it follows HA's configuration. If you don't want that, you can just display the raw state :
```yaml
state_display: '[[[ return entity.state; ]]]'
```

**Comment by db-one** [comment]
ok. thanks, it solved my problem
![image](https://github.com/custom-cards/button-card/assets/20243226/78c85365-0e00-47d8-9447-5d62b0b189e4)

**Comment by db-one** [comment]
> 默认情况下，它遵循 HA 的配置。如果你不想这样，你可以只显示原始状态：
> 
> ```yaml
> state_display: '[[[ return entity.state; ]]]'
> ```



    state_display: '[[[ return entity.state; ]]]'
    numeric_precision: 0



Sorry to bother you, these two parameters conflict with each other,
Added     state_display: '[[[ return entity.state; ]]]'
Then     numeric_precision: 0 , This parameter is invalid. How can I make them valid at the same time? Thank you very much. I hope you can help me.
