### ISSUE TITLE
Password or PIN for button

### ISSUE THREAD

**Issue by dustins1983** [custom-cards/button-card#77]
I have buttons for my garage door opener, it would be awesome if you could implement a way to add a pin for a button press. Like press the button and then it asks for a pin. Would add a layer of security. Thanks

**Comment by RomRider** [comment]
I don't think it belongs here. It can be easily bypassed by using the service call directly.
@iantrich, throughs ?

**Comment by iantrich** [comment]
Use state switch or config-template-card if you want to disable for a user

**Comment by f00dagi** [comment]
@dustins1983: I am looking for this exact functionality myself, did you solve it?

**Comment by johntdyer** [comment]
@iantrich I was wondering if you might be open to re-opening this issue ... I believe there is a gap in functionality for client side "security " for tablets ... there needs to be a card that uses a pin pad for input rather then a keyboard

**Comment by dcapslock** [comment]
Check out https://github.com/custom-cards/button-card/discussions/951 - working PIN code example with button-card
