### ISSUE TITLE
Navigation 

### ISSUE THREAD

**Issue by robertw** [custom-cards/button-card#78]
Great button love it ! could you consider adding the change that Rondom added

- type: "custom:button-card"
      color_type: link-card
      url: /lovelace/7
      name: Climate
      entity:
      icon: mdi:thermometer-lines
      size: 40px
      style:
        - text-transform: none
        - color: black
        - background-color: white
        - font-size: 14px
        - font-weight: normal

That would be very cool .
https://pastebin.com/gRR40zDS

is his code

also 

option 

to add the function of the package 
type: entity-button
name: Turn Off Lights
tap_action:
 action: call-service
 service: script.turn_on
 service_data:
   entity_id: script.turn_off_lights
entity: script.turn_off_lights

that would round out your whole package once again for your time

**Comment by iantrich** [comment]
Duplicate https://github.com/custom-cards/button-card/issues/31
