### ISSUE TITLE
Cards are flickering on scroll and touch-down

### ISSUE THREAD

**Issue by ultimate-tester** [custom-cards/button-card#812]
**Checklist**
- [x] I updated the card to the latest version available
- [x] I cleared the cache of my browser

**Describe the bug**
When refreshing the dashboard (mobile), all cards flicker once in a bright white color. Then, when touching the cards (hold the touch), the cards and somehow other similar cards start flickering.

**Version of the card**
Version: 4.1.1

**To Reproduce**
This is the configuration I used:
```yaml

```

**Screenshots**
The video shows touch and drag. When stop touch, the flickering is gone.
https://github.com/custom-cards/button-card/assets/580758/4123d574-f52f-417f-9764-036f03f710f7

**Expected behavior**
No flickering.

**Smartphone (please complete the following information):**
 - Device: iPhone, I tested various iPhones.
 - OS: 17.1.2

**Additional context**
N/A

**Comment by Mariusthvdb** [comment]
And your (minimal) configuration is?

**Comment by ultimate-tester** [comment]
Working on reducing it to bare minimum and will share it within a few hours :)

**Comment by ultimate-tester** [comment]
Whoops, it's the same as reported in #793! Closing this one.
