### ISSUE TITLE
icons not showing  on February ha beta 

### ISSUE THREAD

**Issue by scooper1** [custom-cards/button-card#828]
- [x ] I updated the card to the latest version available
- [ x] I cleared the cache of my browser

icons not showing  on February ha beta  unless defined in card configuration
The feb beta has lots of changes to how icons work

Version:  v4.1.2-dev 1

**Screenshots**
![image](https://github.com/custom-cards/button-card/assets/14822945/d0ef2e2d-85fc-4be7-87ba-61a9bf7c8027)

**Expected behavior**
all buttons to show icons

**Desktop (please complete the following information):**
  chrome

**Comment by smarthomefamilyverrips** [comment]
@scooper1 it looks like same behavior as the issue I have

**Comment by Mariusthvdb** [comment]
see developer blog https://developers.home-assistant.io/blog/2024/01/30/ha-state-icon-properties-changes/

**Comment by scooper1** [comment]
Thanks for quick response.   All working for me

**Comment by scooper1** [comment]
Fixed in dev 2

**Comment by Nemesis24** [comment]
This is the same with 4.1.2 for me

**Comment by Mariusthvdb** [comment]
clean cache, as always,

button-card is working perfectly now,

**Comment by smarthomefamilyverrips** [comment]
4.1.2 did solve it for me when cssting on google hub and google hub max 👍

**Comment by Mariusthvdb** [comment]
are those `custom:button-card`?
are you sure there's no hint of minimalist or mushroom card there?

because those need updated too in that case

**Comment by smarthomefamilyverrips** [comment]
Did you clear cache, or best just clear all  browser details. Did you try different browsers?

**Comment by DaWheelz** [comment]
> Did you clear cache, or best just clear all browser details. Did you try different browsers?

Yes I tried Firefox and Chrome. Both show the same issue

@Mariusthvdb I am using the Minimalist-UI theme. I hope it will get fixed when those are getting updated.

This is the YAML that I am using for the button-card
`- type: "custom:button-card"
                template:
                  - card_room
                  - blue_no_state
                name: Badkamer
                icon: mdi:shower-head
                show_entity_picture: true
                label: |
                  [[[
                    return states['sensor.temp_vochtigheid_badkamer_temperature'].state + "°C";
                  ]]]
                tap_action:
                  action: navigate
                  navigation_path: "#badkamer"
                variables:
                  label_use_temperature: states['sensor.temp_vochtigheid_badkamer_temperature'].state
                  label_use_brightness: true
                  entity_1:
                    entity_id: light.badkamer_lichten
                    icon: mdi:ceiling-light-multiple-outline
                    templates:
                      - yellow_on
                    tap_action:
                      action: toggle`

**Comment by Mariusthvdb** [comment]
> @Mariusthvdb I am using the Minimalist-UI theme. I hope it will get fixed when those are getting updated.

then why post here, if you know the cause?

**Comment by DaWheelz** [comment]
> > @Mariusthvdb I am using the Minimalist-UI theme. I hope it will get fixed when those are getting updated.
> 
> then why post here, if you know the cause?

I don't know if that is the case. I happened to have the same issue as the other person mentioned above. That why I comment
