### ISSUE TITLE
Fehlermeldung bei input_number

### ISSUE THREAD

**Issue by MicGai** [custom-cards/button-card#892]
Hallo,
ich bin noch recht neu dabei und komme bei diesem Thema nicht weiter.
Ich versuche mit einer Button Card einen Wert (Benzinpreis) an einen weiteren Sensor zu übermitteln.

Ich bekomme jedoch immer eine Fehlermeldung sobald ich es nur anklicke.
Fehlermeldung: "Die Aktion input_number/set_value konnte nicht ausgeführt werden. expected float for dictionary value @ data['value']"

Sensor: input_number.star_preisalarm - erstellt über helper in HA
Atribute: initial: null, editable: false, min: 1.6, max: 1.8, step: 0.01, mode: box, friendly_name: Star Preisalarm

type: custom:button-card
entity: input_number.star_preisalarm
name: "Set Value"
show_state: true
tap_action:
  action: call-service
  service: input_number.set_value
  service_data:
    entity_id: input_number.star_preisalarm
    value: "[[ states['input_number.star_preisalarm'].state | float ]]"

würde mich freuen wenn jemand von euch eine Lösung parat hat.

LG Michael

**Comment by Mariusthvdb** [comment]
please when posting, do it in English. also format your code correctly using the <> buttons in the editor

tot wat we can check your code and help you

**Comment by MicGai** [comment]
Sorry and thank you for information and your Help.
